// Country feed data: 148 countries, each with direct publisher RSS feeds.
// Google News RSS is not used: it throttles Cloudflare Workers egress, so fetches from the worker time out or 503.
// Feed URLs are the post-redirect URLs (redirects cost a Workers subrequest each).

export interface FeedEntry {
  url: string;
  name?: string; // publication name (from upstream)
  category?: string; // upstream category (mapped to our Category at fetch time)
}

export interface CountryData {
  code: string;
  name: string;
  lat: number;
  lng: number;
  // Direct RSS feeds from news outlets in this country
  fallbackFeeds?: (string | FeedEntry)[];
}

export const COUNTRIES: CountryData[] = [
  {
    code: "US",
    name: "United States",
    lat: 39.8,
    lng: -98.5,
    fallbackFeeds: [
      { url: "https://www.espn.com/espn/rss/news", name: "ESPN" },
      { url: "https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml", name: "The New York Times" },
      { url: "https://abcnews.entertainment.syndication.distro.dtci.technology/v1/partner/flipboard?platform=cfa&brand=abcn&type=general&section=top-news", name: "ABCNews.com" },
      { url: "https://www.latimes.com/rss2.0.xml", name: "Los Angeles Times" },
      { url: "https://www.yardbarker.com/rss/rumors", name: "Yardbarker.com" },
      { url: "https://www.forbes.com/business/feed2/", name: "Forbes" },
      { url: "https://www.cnbc.com/id/100003114/device/rss/rss.html", name: "CNBC" },
      { url: "https://www.usmagazine.com/tag/celebrity_news/feed/", name: "UsMagazine.com" },
      { url: "https://www.cbssports.com/rss/headlines/", name: "CBSSports.com" },
      { url: "https://slate.com/feeds/all.rss", name: "Slate Magazine" },
      { url: "https://nypost.com/us-news/feed/", name: "New York Post" },
      { url: "https://feeds.npr.org/1004/rss.xml", name: "NPR : National Public Radio" },
      { url: "https://www.sfgate.com/bayarea/feed/bay-area-news-429.php", name: "SFGate" },
      { url: "https://time.com/feed/", name: "TIME.com" },
      { url: "https://seekingalpha.com/feed.xml", name: "Seeking Alpha" },
      { url: "https://rss.csmonitor.com/feeds/csm", name: "The Christian Science Monitor" },
      { url: "https://techcrunch.com/feed/", name: "TechCrunch" },
      { url: "http://feeds.feedburner.com/breitbart", name: "Breitbart" },
      { url: "https://chaski.huffpost.com/us/auto/vertical/world-news", name: "World News - Breaking News, Top Stories" },
      { url: "https://www.latimes.com/world-nation/rss2.0.xml", name: "World & Nation" },
      { url: "https://rss.politico.com/playbook.xml", name: "Playbook" },
    ],
  },
  {
    code: "GB",
    name: "United Kingdom",
    lat: 54,
    lng: -2,
    fallbackFeeds: [
      { url: "https://feeds.bbci.co.uk/news/rss.xml", name: "BBC" },
      { url: "https://feeds.bbci.co.uk/news/england/rss.xml", name: "BBC News" },
      { url: "https://www.skysports.com/rss/11095", name: "Sky Sports" },
      { url: "https://www.mirror.co.uk/news/?service=rss", name: "Mirror" },
      { url: "https://metro.co.uk/feed/", name: "Metro" },
      { url: "https://www.ft.com/world?format=rss", name: "Financial Times" },
      { url: "https://www.dailyrecord.co.uk/?service=rss", name: "Daily Record" },
      { url: "https://www.manchestereveningnews.co.uk/?service=rss", name: "Manchester Evening News" },
      { url: "https://www.standard.co.uk/news/rss", name: "London Evening Standard" },
      { url: "https://www.walesonline.co.uk/news/wales-news/?service=rss", name: "WalesOnline" },
      { url: "https://www.theguardian.com/world/rss", name: "World news | The Guardian" },
      { url: "https://www.independent.co.uk/news/uk/rss", name: "The Independent" },
      { url: "http://feeds.feedburner.com/daily-express-news-showbiz", name: "Daily Express :: News Feed" },
    ],
  },
  {
    code: "IN",
    name: "India",
    lat: 20.6,
    lng: 78.9,
    fallbackFeeds: [
      { url: "https://timesofindia.indiatimes.com/rssfeeds/-2128838597.cms", name: "Times of India (Mumbai)" },
      { url: "https://timesofindia.indiatimes.com/rssfeeds/-2128839596.cms", name: "Times of India (Delhi)" },
      { url: "https://timesofindia.indiatimes.com/rssfeeds/-2128833038.cms", name: "Times of India (Bangalore)" },
      { url: "https://timesofindia.indiatimes.com/rssfeeds/-2128816011.cms", name: "Times of India (Hyderabad)" },
      { url: "https://timesofindia.indiatimes.com/rssfeeds/2950623.cms", name: "Times of India (Chennai)" },
      { url: "https://timesofindia.indiatimes.com/rssfeeds/-2128821153.cms", name: "Times of India (Ahemdabad)" },
      { url: "https://timesofindia.indiatimes.com/rssfeeds/3947060.cms", name: "Times of India (Allahabad)" },
      { url: "https://timesofindia.indiatimes.com/rssfeeds/4118235.cms", name: "Times of India (Bhubaneswar)" },
      { url: "https://timesofindia.indiatimes.com/rssfeeds/7503091.cms", name: "Times of India (Coimbatore)" },
      { url: "https://timesofindia.indiatimes.com/rssfeeds/6547154.cms", name: "Times of India (Gurgaon)" },
      { url: "https://timesofindia.indiatimes.com/rssfeeds/4118215.cms", name: "Times of India (Guwahati)" },
      { url: "https://timesofindia.indiatimes.com/rssfeeds/3942695.cms", name: "Times of India (Hubli)" },
      { url: "https://timesofindia.indiatimes.com/rssfeeds/3947067.cms", name: "Times of India (Kanpur)" },
      { url: "https://timesofindia.indiatimes.com/rssfeeds/-2128830821.cms", name: "Times of India (Kolkata)" },
      { url: "https://timesofindia.indiatimes.com/rssfeeds/3947051.cms", name: "Times of India (Ludhiana)" },
      { url: "https://timesofindia.indiatimes.com/rssfeeds/3942690.cms", name: "Times of India (Mangalore)" },
      { url: "https://timesofindia.indiatimes.com/rssfeeds/3942693.cms", name: "Times of India (Mysore)" },
      { url: "https://timesofindia.indiatimes.com/rssfeeds/8021716.cms", name: "Times of India (Noida)" },
      { url: "https://timesofindia.indiatimes.com/rssfeeds/-2128821991.cms", name: "Times of India (Pune)" },
      { url: "https://timesofindia.indiatimes.com/rssfeeds/3012535.cms", name: "Times of India (Goa)" },
      { url: "https://timesofindia.indiatimes.com/rssfeeds/-2128816762.cms", name: "Times of India (Chandigarh)" },
      { url: "https://timesofindia.indiatimes.com/rssfeeds/-2128819658.cms", name: "Times of India (Lucknow)" },
      { url: "https://timesofindia.indiatimes.com/rssfeeds/-2128817995.cms", name: "Times of India (Patna)" },
      { url: "https://timesofindia.indiatimes.com/rssfeeds/3012544.cms", name: "Times of India (Jaipur)" },
      { url: "https://timesofindia.indiatimes.com/rssfeeds/442002.cms", name: "Times of India (Nagpur)" },
      { url: "https://timesofindia.indiatimes.com/rssfeeds/3942663.cms", name: "Times of India (Rajkot)" },
      { url: "https://timesofindia.indiatimes.com/rssfeeds/4118245.cms", name: "Times of India (Ranchi)" },
      { url: "https://timesofindia.indiatimes.com/rssfeeds/3942660.cms", name: "Times of India (Surat)" },
      { url: "https://timesofindia.indiatimes.com/rssfeeds/3942666.cms", name: "Times of India (Vadodara)" },
      { url: "https://timesofindia.indiatimes.com/rssfeeds/3947071.cms", name: "Times of India (Varanasi)" },
      { url: "https://timesofindia.indiatimes.com/rssfeeds/3831863.cms", name: "Times of India (Thane)" },
      { url: "https://timesofindia.indiatimes.com/rssfeeds/878156304.cms", name: "Times of India (Thiruvananthapuram)" },
      { url: "https://timesofindia.indiatimes.com/rssfeedstopstories.cms", name: "Times of India (Top Stories)" },
      { url: "https://timesofindia.indiatimes.com/rssfeedmostrecent.cms", name: "Times of India (Most Recent Stories)" },
      { url: "https://timesofindia.indiatimes.com/rssfeeds/-2128936835.cms", name: "Times of India (India)" },
      { url: "https://timesofindia.indiatimes.com/rssfeeds/296589292.cms", name: "Times of India (World)" },
      { url: "https://timesofindia.indiatimes.com/rssfeeds/7098551.cms", name: "Times of India (NRI)" },
      { url: "https://timesofindia.indiatimes.com/rssfeeds/1898055.cms", name: "Times of India (Business)" },
      { url: "https://timesofindia.indiatimes.com/rssfeeds_us/72258322.cms", name: "Times of India (US)" },
      { url: "https://timesofindia.indiatimes.com/rssfeeds/54829575.cms", name: "Times of India (Cricket)" },
      { url: "https://timesofindia.indiatimes.com/rssfeeds/4719148.cms", name: "Times of India (Sports)" },
      { url: "https://timesofindia.indiatimes.com/rssfeeds/-2128672765.cms", name: "Times of India (Science)" },
      { url: "https://timesofindia.indiatimes.com/rssfeeds/2647163.cms", name: "Times of India (Environment)" },
      { url: "https://timesofindia.indiatimes.com/rssfeeds/1081479906.cms", name: "Times of India (Entertainment)" },
      { url: "https://timesofindia.indiatimes.com/rssfeeds/2886704.cms", name: "Times of India (Life & Style)" },
      { url: "https://timesofindia.indiatimes.com/rssfeedmostread.cms", name: "Times of India (Most Read)" },
      { url: "https://timesofindia.indiatimes.com/rssfeedmostshared.cms", name: "Times of India (Most Shared)" },
      { url: "https://timesofindia.indiatimes.com/rssfeeds/65857041.cms", name: "Times of India (Astrology)" },
      { url: "https://timesofindia.indiatimes.com/rssfeeds/30359486.cms", name: "Times of India (US)" },
      { url: "https://timesofindia.indiatimes.com/rssfeeds/2177298.cms", name: "Times of India (UK)" },
      { url: "https://timesofindia.indiatimes.com/rssfeeds/1898274.cms", name: "Times of India (Europe)" },
      { url: "https://timesofindia.indiatimes.com/rssfeeds/671314.cms", name: "Times of India (Rest of World)" },
      { url: "https://feeds.feedburner.com/ndtvnews-top-stories", name: "NDTV (Top Stories)" },
      { url: "https://feeds.feedburner.com/ndtvnews-latest", name: "NDTV (Latest Stories)" },
      { url: "https://feeds.feedburner.com/ndtvnews-trending-news", name: "NDTV (Trending Stories)" },
      { url: "https://feeds.feedburner.com/ndtvnews-india-news", name: "NDTV (India)" },
      { url: "https://feeds.feedburner.com/ndtvnews-world-news", name: "NDTV (World)" },
      { url: "https://feeds.feedburner.com/ndtvprofit-latest", name: "NDTV (Business)" },
      { url: "https://feeds.feedburner.com/ndtvmovies-latest", name: "NDTV (Movies)" },
      { url: "https://feeds.feedburner.com/ndtvsports-latest", name: "NDTV (Sports)" },
      { url: "https://feeds.feedburner.com/ndtvsports-cricket", name: "NDTV (Cricket)" },
      { url: "https://feeds.feedburner.com/gadgets360-latest", name: "NDTV (Tech)" },
      { url: "https://feeds.feedburner.com/ndtvnews-cities-news", name: "NDTV (Cities)" },
      { url: "https://feeds.feedburner.com/ndtvnews-south", name: "NDTV (South)" },
      { url: "https://feeds.feedburner.com/ndtvnews-indians-abroad", name: "NDTV (Indians Abroad)" },
      { url: "https://feeds.feedburner.com/ndtvcooks-latest", name: "NDTV (Health)" },
      { url: "https://feeds.feedburner.com/ndtvnews-offbeat-news", name: "NDTV (Offbeat)" },
      { url: "https://feeds.feedburner.com/ndtvkhabar-latest", name: "NDTV (Hindi)" },
      { url: "https://www.india.com/feed/", name: "India.com" },
      { url: "https://zeenews.india.com/rss/india-national-news.xml", name: "Zee News (Nation)" },
      { url: "https://zeenews.india.com/rss/world-news.xml", name: "Zee News (World)" },
      { url: "https://zeenews.india.com/rss/india-news.xml", name: "Zee News (States)" },
      { url: "https://zeenews.india.com/rss/business.xml", name: "Zee News (Business)" },
      { url: "https://zeenews.india.com/rss/sports-news.xml", name: "Zee News (Sports)" },
      { url: "https://zeenews.india.com/rss/entertainment-news.xml", name: "Zee News (Entertainment)" },
      { url: "https://zeenews.india.com/rss/health-news.xml", name: "Zee News (Health)" },
      { url: "https://zeenews.india.com/rss/technology-news.xml", name: "Zee News (Technology)" },
      { url: "https://www.thehindu.com/sport/feeder/default.rss", name: "The Hindu (Sport)" },
      { url: "https://www.indiatoday.in/rss/home", name: "India Today (Home)" },
      { url: "https://www.indiatoday.in/rss/1206514", name: "India Today (Nation)" },
      { url: "https://www.indiatoday.in/rss/1206551", name: "India Today (Leisure)" },
      { url: "https://www.indiatoday.in/rss/1206509", name: "India Today (Cover Story)" },
      { url: "https://www.indiatoday.in/rss/1206577", name: "India Today (World)" },
      { url: "https://www.indiatoday.in/rss/1206550", name: "India Today (Sport)" },
      { url: "https://www.newslaundry.com/stories.rss", name: "News Laundry" },
      { url: "https://www.bhaskar.com/rss-v1--category-1944.xml", name: "Dainik Bhaskar (Opinion)" },
      { url: "https://www.bhaskar.com/rss-v1--category-11215.xml", name: "Dainik Bhaskar (Bollywood)" },
      { url: "https://www.bhaskar.com/rss-v1--category-11945.xml", name: "Dainik Bhaskar (Jobs & Education)" },
      { url: "https://www.bhaskar.com/rss-v1--category-1532.xml", name: "Dainik Bhaskar (Women)" },
      { url: "https://www.bhaskar.com/rss-v1--category-5707.xml", name: "Dainik Bhaskar (Tech - Auto)" },
      { url: "https://www.bhaskar.com/rss-v1--category-7911.xml", name: "Dainik Bhaskar (Happy Life)" },
      { url: "https://www.bhaskar.com/rss-v1--category-11616.xml", name: "Dainik Bhaskar (Utility)" },
      { url: "https://www.bhaskar.com/rss-v1--category-1125.xml", name: "Dainik Bhaskar (International)" },
      { url: "https://www.bhaskar.com/rss-v1--category-1061.xml", name: "Dainik Bhaskar (National)" },
      { url: "https://www.bhaskar.com/rss-v1--category-1051.xml", name: "Dainik Bhaskar (Business)" },
      { url: "https://www.bhaskar.com/rss-v1--category-1053.xml", name: "Dainik Bhaskar (Sports)" },
      { url: "https://www.bhaskar.com/rss-v1--category-1057.xml", name: "Dainik Bhaskar (Magazine)" },
      { url: "https://www.bhaskar.com/rss-v1--category-3379.xml", name: "Dainik Bhaskar (Jeevan Mantra)" },
      { url: "https://www.bhaskar.com/rss-v1--category-3998.xml", name: "Dainik Bhaskar (Entertainment)" },
      { url: "https://www.bhaskar.com/rss-v1--category-4587.xml", name: "Dainik Bhaskar (DB Original)" },
      { url: "https://www.bhaskar.com/rss-v1--category-1740.xml", name: "Dainik Bhaskar (Rajasthan)" },
      { url: "https://www.bhaskar.com/rss-v1--category-1739.xml", name: "Dainik Bhaskar (Madhya Pradesh)" },
      { url: "https://www.bhaskar.com/rss-v1--category-2052.xml", name: "Dainik Bhaskar (Uttar Pradesh)" },
      { url: "https://www.bhaskar.com/rss-v1--category-3679.xml", name: "Dainik Bhaskar (Bihar)" },
      { url: "https://www.bhaskar.com/rss-v1--category-1741.xml", name: "Dainik Bhaskar (Chhattisgarh)" },
      { url: "https://www.bhaskar.com/rss-v1--category-1742.xml", name: "Dainik Bhaskar (Haryana)" },
      { url: "https://www.bhaskar.com/rss-v1--category-7140.xml", name: "Dainik Bhaskar (New Delhi)" },
      { url: "https://www.bhaskar.com/rss-v1--category-2318.xml", name: "Dainik Bhaskar (Maharashtra)" },
      { url: "https://www.bhaskar.com/rss-v1--category-3682.xml", name: "Dainik Bhaskar (Jharkhand)" },
      { url: "https://www.bhaskar.com/rss-v1--category-1743.xml", name: "Dainik Bhaskar (Punjab)" },
      { url: "https://www.bhaskar.com/rss-v1--category-2314.xml", name: "Dainik Bhaskar (Gujarat)" },
      { url: "https://www.bhaskar.com/rss-v1--category-11649.xml", name: "Dainik Bhaskar (Chandigarh)" },
      { url: "https://www.bhaskar.com/rss-v1--category-12084.xml", name: "Dainik Bhaskar (Himachal)" },
      { url: "https://feeds.bbci.co.uk/news/world/asia/india/rss.xml", name: "BBC News - India" },
      { url: "https://www.theguardian.com/world/india/rss", name: "India | The Guardian" },
      { url: "https://www.sebi.gov.in/sebirss.xml", name: "SEBI RSS Feed" },
      { url: "https://www.dnaindia.com/feeds/india.xml", name: "India News" },
      { url: "https://www.freepressjournal.in/stories.rss", name: "Free Press Journal" },
      { url: "https://www.deccanchronicle.com/feeds.xml", name: "Deccan Chronicle - Latest India news | Breaking news | Hyderabad News | World news | Business news | Politics | Technology news" },
      { url: "https://economictimes.indiatimes.com/rssfeedsdefault.cms", name: "Economic Times" },
      { url: "http://feeds.feedburner.com/ScrollinArticles.rss", name: "Scroll.in" },
      { url: "https://www.thehindubusinessline.com/feeder/default.rss", name: "Business Line - Home" },
      { url: "http://feeds.feedburner.com/techgenyz", name: "TechGenyz" },
      { url: "https://prod-qt-images.s3.amazonaws.com/production/swarajya/feed.xml", name: "Swarajya" },
      { url: "https://www.amarujala.com/rss/breaking-news.xml", name: "Latest And Breaking Hindi News Headlines, News In Hindi | अमर उजाला हिंदी न्यूज़ | - Amar Ujala" },
      { url: "https://www.bhaskar.com/rss-feed/1061/", name: "देश | दैनिक भास्कर" },
      { url: "https://www.divyabhaskar.co.in/rss-feed/1037/", name: "ઈન્ડિયા | દિવ્ય ભાસ્કર" },
    ],
  },
  {
    code: "AU",
    name: "Australia",
    lat: -25.3,
    lng: 133.8,
    fallbackFeeds: [
      { url: "https://www.abc.net.au/news/feed/46182/rss.xml", name: "ABC" },
      { url: "https://www.theage.com.au/rss/feed.xml", name: "The Age" },
      { url: "https://www.brisbanetimes.com.au/rss/feed.xml", name: "Brisbane Times" },
      { url: "https://www.smh.com.au/rss/feed.xml", name: "Sydney Morning Herald - Latest News" },
      { url: "https://www.abc.net.au/news/feed/1948/rss.xml", name: "ABC News" },
      { url: "https://www.perthnow.com.au/news/feed", name: "PerthNow" },
      { url: "https://www.canberratimes.com.au/rss.xml", name: "The Canberra Times - Local News" },
      { url: "https://www.businessnews.com.au/rssfeed/latest.rss", name: "Business News - Latest Headlines" },
    ],
  },
  {
    code: "CA",
    name: "Canada",
    lat: 56.1,
    lng: -106.3,
    fallbackFeeds: [
      { url: "https://ici.radio-canada.ca/info/rss/info/a-la-une", name: "Radio Canada" },
      { url: "https://nationalpost.com/feed", name: "National Post" },
      { url: "https://torontosun.com/category/news/feed.xml", name: "Toronto Sun" },
      { url: "https://globalnews.ca/feed/", name: "Global News" },
      { url: "https://calgaryherald.com/feed", name: "Calgary Herald" },
      { url: "https://torontosun.com/feed", name: "Vancouver Sun" },
      { url: "https://edmontonjournal.com/feed", name: "Edmonton Journal" },
      { url: "https://ottawacitizen.com/feed", name: "Ottawa Citizen" },
      { url: "https://edmontonsun.com/feed", name: "Edmonton Sun" },
      { url: "https://calgarysun.com/feed", name: "Calgary Sun" },
      { url: "https://o.canada.com/feed", name: "Canada.com" },
      { url: "http://feeds.feedburner.com/FP_TopStories", name: "Financial Post" },
      { url: "https://theprovince.com/feed", name: "Province" },
      { url: "https://www.winnipegfreepress.com/breakingnews/feed", name: "Winnipeg Free Press" },
      { url: "https://thetyee.ca/rss2.xml", name: "The Tyee" },
      { url: "https://www.nationalobserver.com/front/rss", name: "The National Observer" },
      { url: "https://www.dailyheraldtribune.com/feed", name: "Grande Prairie Daily Herald" },
      { url: "https://financialpost.com/feed", name: "Financial Post" },
    ],
  },
  {
    code: "DE",
    name: "Germany",
    lat: 51.2,
    lng: 10.4,
    fallbackFeeds: [
      { url: "https://www.welt.de/feeds/latest.rss", name: "DIE WELT" },
      { url: "https://rss.sueddeutsche.de/rss/Wirtschaft", name: "Sueddeutsche.de" },
      { url: "https://www.stern.de/feed/standard/all/", name: "STERN" },
      { url: "http://newsfeed.zeit.de/index", name: "ZEIT" },
      { url: "https://www.faz.net/rss/aktuell/", name: "Frankfurter Allgemeine" },
      { url: "https://www.abendblatt.de/rss", name: "Hamburger Abendblatt" },
      { url: "https://rp-online.de/feed.rss", name: "RP ONLINE" },
      { url: "https://www.tagesschau.de/infoservices/alle-meldungen-100~rss2.xml", name: "ARD Tagesschau" },
    ],
  },
  {
    code: "FR",
    name: "France",
    lat: 46.2,
    lng: 2.2,
    fallbackFeeds: [
      { url: "https://www.france24.com/fr/rss", name: "France 24" },
      { url: "https://www.lemonde.fr/rss/une.xml", name: "Le Monde" },
      { url: "https://www.lefigaro.fr/rss/figaro_actualites.xml", name: "Le Figaro" },
      { url: "https://www.rfi.fr/fr/france/rss", name: "RFI" },
      { url: "https://feeds.leparisien.fr/leparisien/rss", name: "Le Parisien" },
      { url: "https://www.liberation.fr/arc/outboundfeeds/rss-all/?outputType=xml", name: "Liberation" },
      { url: "https://www.mediapart.fr/articles/feed", name: "Mediapart" },
      { url: "https://feeds.thelocal.com/rss/fr", name: "The Local" },
      { url: "https://www.20minutes.fr/feeds/rss-une.xml", name: "20 Minutes" },
      { url: "https://dwh.lequipe.fr/api/edito/rss?path=/", name: "L'Équipe" },
      { url: "https://www.humanite.fr/feed", name: "L'Humanité" },
      { url: "https://www.la-croix.com/feeds/rss/site.xml", name: "La Croix" },
      { url: "https://www.nouvelobs.com/rss.xml", name: "Le Nouvel Obs (L'Obs)" },
      { url: "https://www.leprogres.fr/rss", name: "Le Progrès" },
      { url: "https://www.dna.fr/rss", name: "Les Dernières Nouvelles d'Alsace (DNA)" },
      { url: "https://www.franceinfo.fr/titres.rss", name: "Franceinfo" },
      { url: "https://www.ouest-france.fr/rss/france", name: "Ouest France" },
      { url: "https://www.france24.com/en/rss", name: "france24.com" },
      { url: "https://www.nouvelobs.com/a-la-une/rss.xml", name: "L'Obs - A la une" },
      { url: "https://www.ladepeche.fr/rss.xml", name: "La Dépêche du Midi : actualités et info en direct de la région Occitanie et des environs - ladepeche.fr" },
      { url: "https://www.sudouest.fr/essentiel/rss.xml", name: "L&#039;essentiel" },
      { url: "https://www.ouest-france.fr/rss/une", name: "Ouest-France - Actualité" },
    ],
  },
  {
    code: "JP",
    name: "Japan",
    lat: 36.2,
    lng: 138.3,
    fallbackFeeds: [
      { url: "https://www.dailymail.com/sport/index.rss", name: "Daily Sports Online" },
      { url: "https://www.nikkansports.com/soccer/atom.xml", name: "nikkansports.com" },
      { url: "https://news.livedoor.com/topics/rss/int.xml", name: "livedoor News" },
      { url: "https://japantoday.com/feed", name: "Japan Today" },
      { url: "http://www.newsonjapan.com/rss/top.xml", name: "News On Japan" },
      { url: "http://feeds.feedburner.com/SdJapan", name: "BRIDGE（ブリッジ）テクノロジー＆スタートアップ情報" },
      { url: "https://news.livedoor.com/topics/rss/top.xml", name: "ライブドアニュース - 主要トピックス" },
    ],
  },
  {
    code: "BR",
    name: "Brazil",
    lat: -14.2,
    lng: -51.9,
    fallbackFeeds: [
      { url: "https://veja.abril.com.br/feed/", name: "Veja" },
      { url: "https://g1.globo.com/rss/g1/", name: "G1" },
      { url: "https://extra.globo.com/rss/extra", name: "Extra" },
      { url: "https://jornaldebrasilia.com.br/feed/", name: "Jornal de Brasília" },
      { url: "https://atarde.com.br/rss", name: "A Tarde" },
      { url: "https://feeds.bbci.co.uk/portuguese/rss.xml", name: "BBC Brasil" },
      { url: "https://jc.uol.com.br/ultimas/rss.xml", name: "Jornal do Comércio" },
      { url: "https://agenciabrasil.ebc.com.br/rss/ultimasnoticias/feed.xml", name: "Agência Brasil" },
      { url: "https://www.riotimesonline.com/feed/", name: "The Rio Times" },
    ],
  },
  {
    code: "MX",
    name: "Mexico",
    lat: 23.6,
    lng: -102.6,
    fallbackFeeds: [
      { url: "http://feeds.feedburner.com/SDPnoticiascom", name: "SDPnoticias.com" },
      { url: "https://www.theguardian.com/world/mexico/rss", name: "Mexico | The Guardian" },
      { url: "https://vanguardia.com.mx/rss.xml", name: "Lo último en Vanguardia MX" },
      { url: "https://www.elsiglodetorreon.com.mx/index.xml", name: "Portada, El Siglo de Torreón" },
      { url: "https://www.elfinanciero.com.mx/arc/outboundfeeds/rss/?outputType=xml", name: "El Financiero" },
      { url: "https://www.informador.mx/rss/ultimas-noticias.xml", name: "El Informador :: Noticias de Jalisco, México, Deportes & Entretenimiento" },
      { url: "https://mexiconewsdaily.com/feed/", name: "Mexico News Daily" },
      { url: "https://8columnas.com.mx/feed/", name: "8 Columnas" },
    ],
  },
  {
    code: "ZA",
    name: "South Africa",
    lat: -30.6,
    lng: 22.9,
    fallbackFeeds: [
      { url: "https://rss.nytimes.com/services/xml/rss/nyt/Business.xml", name: "Business Day" },
      { url: "https://techcentral.co.za/feed/", name: "TechCentral" },
      { url: "https://www.dailymaverick.co.za/dmrss/", name: "Daily Maverick" },
      { url: "https://www.moneyweb.co.za/feed/", name: "Moneyweb" },
      { url: "https://rss.iol.io/iol/news", name: "IOL section feed for News" },
      { url: "https://www.thesouthafrican.com/feed/", name: "The South African" },
      { url: "https://api.axios.com/feed/", name: "Axios" },
    ],
  },
  {
    code: "NG",
    name: "Nigeria",
    lat: 9.1,
    lng: 8.7,
    fallbackFeeds: [
      { url: "http://feeds.feedburner.com/Nigerianeye", name: "Nigerian News. Latest Nigeria News. Your online Nigerian Newspaper." },
      { url: "https://www.legit.ng/rss/all.rss", name: "Legit.ng" },
      { url: "https://dailypost.ng/feed/", name: "Daily Post Nigeria" },
      { url: "https://www.premiumtimesng.com/feed", name: "Premium Times Nigeria" },
    ],
  },
  {
    code: "KE",
    name: "Kenya",
    lat: -0.02,
    lng: 37.9,
    fallbackFeeds: [
      { url: "https://nation.africa/kenya/rss.xml", name: "| Daily Nation" },
      { url: "https://www.standardmedia.co.ke/rss/headlines.php", name: "The Standard News Feeds" },
      { url: "https://www.kenyans.co.ke/feeds/news", name: "Kenyans.co.ke" },
      { url: "https://capitalfm.africa/news/feed/", name: "News &#8211; Capital FM Kenya" },
    ],
  },
  {
    code: "EG",
    name: "Egypt",
    lat: 26.8,
    lng: 30.8,
    fallbackFeeds: [
      { url: "https://www.madamasr.com/en/feed/", name: "Mada Masr" },
      { url: "https://www.youm7.com/rss/SectionRss?SectionID=65", name: "rss-أخبار عاجلة" },
      { url: "https://www.dailynewsegypt.com/feed/", name: "Dailynewsegypt" },
    ],
  },
  {
    code: "IL",
    name: "Israel",
    lat: 31,
    lng: 34.9,
    fallbackFeeds: [
      { url: "https://www.ynet.co.il/Integration/StoryRss3082.xml", name: "Ynet" },
      { url: "https://www.ynetnews.com/Integration/StoryRss3082.xml", name: "ynetnews - News" },
      { url: "https://www.timesofisrael.com/feed/", name: "The Times of Israel" },
      { url: "https://www.jpost.com/rss/rssfeedsfrontpage.aspx", name: "jpost.com" },
      { url: "https://www.israelhayom.com/feed/", name: "www.israelhayom.com" },
    ],
  },
  {
    code: "AE",
    name: "UAE",
    lat: 23.4,
    lng: 53.8,
    fallbackFeeds: [
      { url: "https://www.khaleejtimes.com/stories.rss", name: "khaleejtimes-english" },
      { url: "https://gulfnews.com/stories.rss", name: "gulfnews" },
      { url: "https://www.thenationalnews.com/arc/outboundfeeds/rss/?outputType=xml", name: "The National" },
    ],
  },
  {
    code: "SA",
    name: "Saudi Arabia",
    lat: 23.9,
    lng: 45.1,
    fallbackFeeds: [
      { url: "https://www.arabnews.com/rss.xml", name: "Arab News" },
      { url: "https://saudigazette.com.sa/rssFeed/74", name: "https://saudigazette.com.sa" },
    ],
  },
  {
    code: "KR",
    name: "South Korea",
    lat: 35.9,
    lng: 127.8,
    fallbackFeeds: [
      { url: "http://rss.donga.com/sports.xml", name: "DongA.com" },
      { url: "https://www.hani.co.kr/rss/english_edition", name: "전체기사 : English Edition : 뉴스 : 한겨레 뉴스 - 인터넷한겨레" },
      { url: "https://en.yna.co.kr/RSS/news.xml", name: "Yonhap News Agency | All News" },
      { url: "https://feed.koreatimes.co.kr/k/southkorea.xml?utm_source=legacy_url&utm_medium=redirect&utm_campaign=legacy_rss", name: "Korea Times News" },
    ],
  },
  {
    code: "SG",
    name: "Singapore",
    lat: 1.35,
    lng: 103.8,
    fallbackFeeds: [
      { url: "https://www.straitstimes.com/news/singapore/rss.xml", name: "The Straits Times World News" },
      { url: "https://www.channelnewsasia.com/api/v1/rss-outbound-feed?_format=xml", name: "Latest News" },
      { url: "https://mothership.sg/feed/", name: "mothership.sg" },
      { url: "https://www.businesstimes.com.sg/rss/top-stories", name: "Top Stories Feed" },
    ],
  },
  {
    code: "ID",
    name: "Indonesia",
    lat: -0.8,
    lng: 113.9,
    fallbackFeeds: [
      { url: "https://www.republika.co.id/rss/", name: "Republika Online RSS Feed" },
      { url: "https://www.antaranews.com/rss/terkini.xml", name: "Berita Terkini - ANTARA News" },
      { url: "https://www.cnnindonesia.com/nasional/rss", name: "CNN Indonesia | Berita Terkini Nasional" },
      { url: "https://en.antaranews.com/rss/news.xml", name: "ANTARA News - Latest Indonesia News" },
    ],
  },
  {
    code: "RU",
    name: "Russia",
    lat: 61.5,
    lng: 105.3,
    fallbackFeeds: [
      { url: "https://ria.ru/export/rss2/index.xml", name: "RIA Novosti" },
      { url: "https://lenta.ru/rss", name: "Lenta.ru : Новости" },
      { url: "https://www.mk.ru/rss/index.xml", name: "Все материалы - Московский Комсомолец" },
      { url: "https://rg.ru/xml/index.xml", name: "Российская Газета" },
      { url: "https://www.rt.com/rss/", name: "RT - Daily news" },
      { url: "https://meduza.io/rss/all", name: "Meduza.io" },
      { url: "https://www.themoscowtimes.com/rss/news", name: "The Moscow Times - Independent News From Russia" },
    ],
  },
  {
    code: "IT",
    name: "Italy",
    lat: 41.9,
    lng: 12.6,
    fallbackFeeds: [
      { url: "https://www.ansa.it/sito/ansait_rss.xml", name: "RSS di   - ANSA.it" },
      { url: "https://www.liberoquotidiano.it/rss.xml", name: "Libero Quotidiano" },
      { url: "https://www.ilmattino.it/?sez=XML&args&p=search&args[box]=Home&limit=20&layout=rss", name: "Il Mattino Web" },
      { url: "https://www.milannews.it/rss/", name: "Milan News" },
      { url: "https://www.internazionale.it/sitemaps/rss.xml", name: "Internazionale" },
      { url: "https://www.theguardian.com/world/italy/rss", name: "Italy | The Guardian" },
    ],
  },
  {
    code: "ES",
    name: "Spain",
    lat: 40.5,
    lng: -3.7,
    fallbackFeeds: [
      { url: "https://feeds.elpais.com/mrss-s/pages/ep/site/elpais.com/portada", name: "EL PAIS" },
      { url: "https://www.abc.es/rss/atom/portada/", name: "ABC" },
      { url: "https://e00-elmundo.uecdn.es/rss/portada.xml", name: "elmundo.es" },
      { url: "https://www.antena3.com/noticias/rss/4013050.xml", name: "Antena 3" },
      { url: "https://www.lavanguardia.com/rss/home.xml", name: "LaVanguardia.com" },
      { url: "https://feeds.elpais.com/mrss-s/pages/ep/site/cincodias.elpais.com/section/ultimas-noticias/portada", name: "Cinco Dias" },
      { url: "https://e00-expansion.uecdn.es/rss/portada.xml", name: "Diario Expansion" },
      { url: "https://rss.elconfidencial.com/espana/", name: "El Confidencial" },
      { url: "https://www.eldiario.es/rss", name: "elDiario.es" },
      { url: "https://www.eldebate.com/rss/home.xml", name: "El Debate" },
      { url: "https://www.elcorreo.com/rss/atom/portada/", name: "elcorreo.com" },
      { url: "https://www.lavozdegalicia.es/index.xml", name: "La Voz de Galicia" },
      { url: "https://www.laregion.es/rss/", name: "La Región" },
      { url: "https://www.elnortedecastilla.es/rss/atom/portada/", name: "El Norte de Castilla" },
      { url: "https://www.huffingtonpost.es/feeds/index.xml", name: "huffingtonpost.es" },
    ],
  },
  {
    code: "PL",
    name: "Poland",
    lat: 51.9,
    lng: 19.1,
    fallbackFeeds: [
      { url: "https://pogoda.interia.pl/feed", name: "INTERIA.PL" },
      { url: "https://wiadomosci.onet.pl/.feed", name: "Onet Wiadomosci" },
      { url: "https://wiadomosci.wp.pl/rss.xml", name: "WP.pl Wiadomosci" },
      { url: "https://wyborcza.pl/pub/rss/najnowsze_wyborcza.xml", name: "Gazeta Wyborcza" },
      { url: "https://sport.tvp.pl/sport.tvp.pl/rss+xml.php", name: "TVP" },
      { url: "https://www.rp.pl/rss_main", name: "Rzeczpospolita" },
      { url: "http://rss.dziennik.pl/Dziennik-Wiadomosci", name: "Dziennik.pl" },
      { url: "https://www.newsweek.pl/rss.xml", name: "Newsweek Polska" },
      { url: "http://rss.dziennik.pl/Dziennik-PL/", name: "Dziennik.pl Dziennik - dziennik.pl" },
      { url: "https://www.wirtualnemedia.pl/rss/aktualnosci", name: "www.wirtualnemedia.pl" },
      { url: "http://rss.gazetaprawna.pl/GazetaPrawna", name: "GazetaPrawna.pl - biznes, podatki, prawo, finanse, wiadomości, praca" },
      { url: "https://www.rp.pl/rss_main?unknown-old-rss", name: "https://www.rp.pl" },
      { url: "https://www.rmf24.pl/feed", name: "RMF24.pl" },
    ],
  },
  {
    code: "UA",
    name: "Ukraine",
    lat: 48.4,
    lng: 31.2,
    fallbackFeeds: [
      { url: "https://gazeta.ua/ru/rss", name: "Gazeta.ua" },
      { url: "https://kp.ua/rss/feed.xml", name: "Komsomolskaya pravda" },
      { url: "https://comments.ua/export/rss_ru.xml", name: "comments.ua" },
      { url: "https://tsn.ua/rss/full.rss", name: "Новини на tsn.ua" },
      { url: "https://nv.ua/rss/all.xml", name: "НВ" },
      { url: "https://rss.unian.net/site/news_rus.rss", name: "Информационное агентство УНИАН" },
      { url: "https://espreso.tv/rss", name: "Еспресо - український погляд на світ!" },
      { url: "https://gazeta.ua/rss", name: "Gazeta.ua" },
    ],
  },
  {
    code: "AR",
    name: "Argentina",
    lat: -38.4,
    lng: -63.6,
    fallbackFeeds: [
      { url: "https://www.clarin.com/rss/lo-ultimo/", name: "Clarin" },
      { url: "https://www.lanacion.com.ar/arc/outboundfeeds/rss/?outputType=xml", name: "La Nacion" },
      { url: "https://www.perfil.com/feed", name: "Perfil.com" },
      { url: "https://www.cronista.com/arc/outboundfeeds/news/", name: "El Cronista" },
      { url: "https://eleconomista.com.ar/ultimas-noticias/feed/", name: "El Economista" },
      { url: "https://www.lapoliticaonline.com/files/rss/ultimasnoticias.xml", name: "La Politica Online" },
      { url: "https://www.ole.com.ar/rss/ultimas-noticias", name: "Ole" },
      { url: "https://feeds.feedburner.com/LaGaceta-General", name: "La Gaceta" },
      { url: "https://www.eldia.com/.rss", name: "El dia" },
      { url: "https://elintransigente.com/feed/", name: "El intransigente" },
      { url: "https://derechadiario.com.ar/rss", name: "La Derecha Diario" },
      { url: "https://www.batimes.com.ar/feed", name: "Buenos Aires Times" },
      { url: "https://buenosairesherald.com/feed/atom", name: "Buenos Aires Herald" },
    ],
  },
  {
    code: "CO",
    name: "Colombia",
    lat: 4.6,
    lng: -74.3,
    fallbackFeeds: [
      { url: "https://www.elcolombiano.com/rss/inicio.xml", name: "El Colombiano" },
      { url: "https://colombiareports.com/feed/", name: "Colombia News" },
      { url: "https://www.semana.com/arc/outboundfeeds/rss/?outputType=xml", name: "Semana" },
    ],
  },
  {
    code: "PH",
    name: "Philippines",
    lat: 12.9,
    lng: 121.8,
    fallbackFeeds: [
      { url: "https://www.philstar.com/rss/entertainment", name: "PhilSTAR.com" },
      { url: "https://interaksyon.philstar.com/feed/", name: "Interaksyon" },
      { url: "https://www.philstar.com/rss/headlines", name: "philstar.com - RSS Headlines" },
      { url: "https://data.gmanews.tv/gno/rss/news/feed.xml", name: "GMA News Online / News" },
      { url: "https://www.topgear.com.ph/feed/rss1", name: "Top Gear: The Philippine authority on cars and the automotive industry" },
      { url: "https://tonite.abante.com.ph/feed/", name: "Abante Tonite" },
    ],
  },
  {
    code: "TW",
    name: "Taiwan",
    lat: 23.7,
    lng: 121,
    fallbackFeeds: [
      { url: "https://news.ltn.com.tw/rss/all.xml", name: "即時新聞 - 自由時報" },
      { url: "https://feeds.feedburner.com/rsscna/intworld", name: "中央社即時新聞 國際焦點" },
      { url: "https://newtalk.tw/rss/all", name: "新頭殼站上新聞" },
    ],
  },
  {
    code: "TH",
    name: "Thailand",
    lat: 15.9,
    lng: 100.5,
    fallbackFeeds: [
      { url: "https://www.khaosodenglish.com/feed/", name: "Khaosod English" },
      { url: "https://thethaiger.com/feed", name: "Thaiger" },
      { url: "https://www.bangkokpost.com/rss/data/topstories.xml", name: "Bangkokpost.com : Top Stories" },
    ],
  },
  {
    code: "AT",
    name: "Austria",
    lat: 47.5,
    lng: 14.6,
    fallbackFeeds: [
      { url: "https://www.krone.at/Nachrichten/rss.html", name: "Krone.at" },
      { url: "https://www.kleinezeitung.at/rss/rubriken/wirtschaft", name: "Kleine Zeitung" },
      { url: "https://www.diepresse.com/rss/Wirtschaft", name: "DiePresse.com" },
      { url: "https://www.nachrichten.at/storage/rss/rss/wirtschaft.xml", name: "Nachrichten.at" },
      { url: "https://www.tt.com/rss/news.xml", name: "Tiroler Tageszeitung" },
      { url: "https://www.laola1.at/storage/rss/laola1-at-news.xml", name: "LAOLA1.at" },
    ],
  },
  {
    code: "CH",
    name: "Switzerland",
    lat: 46.8,
    lng: 8.2,
    fallbackFeeds: [
      { url: "https://partner-feeds.publishing.tamedia.ch/rss/tagesanzeiger/", name: "Tages Anzeiger" },
      { url: "https://www.nzz.ch/startseite.rss", name: "Neue Zuercher Zeitung" },
      { url: "https://www.srf.ch/sport/bnf/rss/718", name: "SRF Sport" },
      { url: "https://partner-feeds.publishing.tamedia.ch/rss/24heures/", name: "24 heures" },
      { url: "https://partner-feeds.publishing.tamedia.ch/rss/bernerzeitung/", name: "Berner Zeitung" },
      { url: "https://partner-feeds.publishing.tamedia.ch/rss/tdg/", name: "Tribune de Geneve" },
    ],
  },
  {
    code: "BE",
    name: "Belgium",
    lat: 50.9,
    lng: 4.4,
    fallbackFeeds: [
      { url: "https://www.lalibre.be/arc/outboundfeeds/rss/?outputType=xml", name: "La Libre" },
      { url: "https://www.dhnet.be/arc/outboundfeeds/rss/?outputType=xml", name: "DH" },
      { url: "https://www.demorgen.be/in-het-nieuws/rss.xml", name: "De Morgen" },
      { url: "https://rss.rtbf.be/article/rss/highlight_rtbf_info.xml?source=internal", name: "RTBF" },
      { url: "https://www.hln.be/home/rss.xml", name: "HLN" },
      { url: "https://www.7sur7.be/home/rss.xml", name: "7sur7" },
    ],
  },
  {
    code: "NL",
    name: "Netherlands",
    lat: 52.1,
    lng: 5.3,
    fallbackFeeds: [
      { url: "https://www.nu.nl/rss/algemeen", name: "nu.nl" },
      { url: "https://feeds.nos.nl/nosnieuwsalgemeen", name: "NOS.nl" },
      { url: "https://www.ad.nl/home/rss.xml", name: "AD.nl" },
      { url: "https://www.volkskrant.nl/sport/rss.xml", name: "Volkskrant" },
      { url: "https://www.nrc.nl/rss/", name: "NRC" },
      { url: "https://www.omroepbrabant.nl/rss", name: "Omroep Brabant" },
    ],
  },
  {
    code: "IE",
    name: "Ireland",
    lat: 53.1,
    lng: -7.7,
    fallbackFeeds: [
      { url: "https://www.independent.ie/irish-news/rss/", name: "Irish Independent" },
      { url: "https://www.thejournal.ie/feed/", name: "TheJournal.ie" },
      { url: "https://www.donegaldaily.com/feed", name: "Donegal Daily" },
      { url: "http://highlandradio.com/feed/", name: "Highland Radio" },
      { url: "https://www.the42.ie/feed/", name: "The42" },
      { url: "https://feeds.feedburner.com/ietopstories", name: "IrishExaminer.com" },
      { url: "https://www.irishmirror.ie/?service=rss", name: "Irish Mirror - Home" },
    ],
  },
  {
    code: "PT",
    name: "Portugal",
    lat: 39.4,
    lng: -8.2,
    fallbackFeeds: [
      { url: "https://rss.impresa.pt/feed/latest/expresso.rss?type=ARTICLE,VIDEO,GALLERY,STREAM,PLAYLIST,EVENT,NEWSLETTER&limit=20&pubsubhub=true", name: "Expresso" },
      { url: "https://feeds.feedburner.com/PublicoRSS", name: "Público" },
      { url: "https://www.cmjornal.pt/rss", name: "Correio da Manhã" },
      { url: "https://www.record.pt/rss/", name: "Jornal Record" },
      { url: "https://tvi.iol.pt/rss.xml", name: "TVI" },
      { url: "https://www.noticiasaominuto.com.br/rss/ultima-hora", name: "Notícias ao Minuto" },
      { url: "https://www.iol.pt/rss.xml", name: "IOL" },
      { url: "https://www.jornaldenegocios.pt/rss", name: "Jornal de Negocios" },
      { url: "https://observador.pt/feed/", name: "Observador" },
      { url: "https://feeds.feedburner.com/asbeiras", name: "Diário As Beiras" },
      { url: "https://www.diariocoimbra.pt/feed/", name: "Diário de Coimbra" },
    ],
  },
  {
    code: "SE",
    name: "Sweden",
    lat: 60.1,
    lng: 18.6,
    fallbackFeeds: [
      { url: "https://feeds.expressen.se/nyheter/", name: "Expressen" },
      { url: "https://www.svt.se/rss.xml", name: "SVT" },
      { url: "https://www.di.se/rss/", name: "di.se" },
      { url: "https://www.sydsvenskan.se/rss.xml?type=section&id=528225", name: "Sydsvenskan" },
      { url: "http://rss.nwt.se/nwtse_karlstad", name: "nwt.se" },
    ],
  },
  {
    code: "NO",
    name: "Norway",
    lat: 60.5,
    lng: 8.5,
    fallbackFeeds: [
      { url: "https://www.vg.no/rss/feed/?limit=10&format=rss&categories=&keywords=", name: "VG Nett" },
      { url: "https://www.nrk.no/nyheter/siste.rss", name: "NRK" },
      { url: "https://www.bt.no/rss/", name: "Bergens Tidende" },
      { url: "https://www.aftenbladet.no/rss/", name: "Stavanger Aftenbladet" },
    ],
  },
  {
    code: "CZ",
    name: "Czechia",
    lat: 49.8,
    lng: 15.5,
    fallbackFeeds: [
      { url: "http://feeds.feedburner.com/penize?format=xml", name: "Penize.cz" },
      { url: "https://www.irozhlas.cz/rss/irozhlas", name: "iROZHLAS.cz" },
      { url: "https://english.radio.cz/rcz-rss/en", name: "Radio Prague International - latest articles" },
      { url: "https://www.novinky.cz/rss", name: "Novinky - nejnovější články" },
      { url: "https://denikn.cz/feed/", name: "Deník N" },
      { url: "https://ct24.ceskatelevize.cz/rss/tema/vyber-redakce-84313", name: "ČT24 — Výběr redakce" },
    ],
  },
  {
    code: "SK",
    name: "Slovakia",
    lat: 48.7,
    lng: 19.7,
    fallbackFeeds: [
      { url: "https://spravy.stvr.sk/feed/", name: "Slovenská televízia a rozhlas (STVR)" },
      { url: "https://www.teraz.sk/rss/rss-vsetky-spravy.rss", name: "TERAZ.sk" },
    ],
  },
  {
    code: "HU",
    name: "Hungary",
    lat: 47.2,
    lng: 19.5,
    fallbackFeeds: [
      { url: "https://hvg.hu/rss", name: "HVG" },
      { url: "https://telex.hu/rss", name: "Telex RSS: Legfrissebb" },
      { url: "https://dailynewshungary.com/feed/", name: "DailyNewsHungary" },
      { url: "https://hungarytoday.hu/feed/", name: "Hungary Today" },
      { url: "https://444.hu/feed", name: "444" },
      { url: "https://index.hu/24ora/rss/", name: "Index - 24óra" },
    ],
  },
  {
    code: "RO",
    name: "Romania",
    lat: 45.9,
    lng: 24.9,
    fallbackFeeds: [
      { url: "http://www.tvr.ro/rss/stiri.xml", name: "Televiziunea Română (TVR)" },
      { url: "https://www.biziday.ro/feed/", name: "biziday" },
    ],
  },
  {
    code: "BG",
    name: "Bulgaria",
    lat: 42.7,
    lng: 25.5,
    fallbackFeeds: [
      { url: "https://www.mediapool.bg/feed/", name: "Mediapool.bg" },
    ],
  },
  {
    code: "RS",
    name: "Serbia",
    lat: 44,
    lng: 21,
    fallbackFeeds: [
      { url: "https://www.blic.rs/rss/danasnje-vesti", name: "Blic" },
      { url: "https://www.novosti.rs/rss/rss-vesti", name: "Novosti" },
      { url: "https://www.rts.rs/vesti/rss.html", name: "RTS" },
      { url: "https://n1info.rs/feed/", name: "Televizija N1" },
    ],
  },
  {
    code: "SI",
    name: "Slovenia",
    lat: 46.2,
    lng: 15,
    fallbackFeeds: [
      { url: "https://www.delo.si/rss/", name: "Delo" },
    ],
  },
  {
    code: "LV",
    name: "Latvia",
    lat: 56.9,
    lng: 24.6,
    fallbackFeeds: [
      { url: "https://www.gorod.lv/rss-news.php", name: "Gorod.lv" },
    ],
  },
  {
    code: "LT",
    name: "Lithuania",
    lat: 55.2,
    lng: 23.9,
    fallbackFeeds: [
      { url: "https://www.15min.lt/rss", name: "15min.lt" },
    ],
  },
  {
    code: "GR",
    name: "Greece",
    lat: 39.1,
    lng: 21.8,
    fallbackFeeds: [
      { url: "http://feeds.feedburner.com/newsbombgr", name: "Newsbomb.gr" },
      { url: "https://www.tovima.gr/category/politics/feed/", name: "To Vima" },
    ],
  },
  {
    code: "LB",
    name: "Lebanon",
    lat: 33.9,
    lng: 35.9,
    fallbackFeeds: [
      { url: "https://www.lbcgroup.tv/Rss/News/en", name: "LBCI Latest News" },
      { url: "https://the961.com/feed/", name: "961" },
      { url: "https://beirut-today.com/feed/", name: "Beirut Today" },
    ],
  },
  {
    code: "MA",
    name: "Morocco",
    lat: 31.8,
    lng: -7.1,
    fallbackFeeds: [
      { url: "https://hihi2.com/feed", name: "hihi2" },
    ],
  },
  {
    code: "TR",
    name: "Turkey",
    lat: 39,
    lng: 35.2,
    fallbackFeeds: [
      { url: "https://www.gazetevatan.com/rss/gundem.xml", name: "Vatan" },
      { url: "https://www.sabah.com.tr/rss/anasayfa.xml", name: "Sabah" },
      { url: "https://www.mynet.com/haber/rss/sondakika", name: "mynet haber" },
      { url: "https://www.haberturk.com/haberturk.xml", name: "Haber Turk" },
      { url: "http://sondakika.haber7.com/sondakika.rss", name: "haber7.com" },
      { url: "https://rss.haberler.com/rssnew.aspx?konu=guncel", name: "Haberler.com" },
      { url: "https://www.fotomac.com.tr/rss/besiktas.xml", name: "FotoMac" },
      { url: "https://www.sporx.com/_xml/rss.php", name: "sporx" },
      { url: "https://www.star.com.tr/rss/rss.asp", name: "STAR" },
      { url: "https://www.cumhuriyet.com.tr/rss", name: "Cumhuriyet.com.tr: Son Dakika" },
      { url: "https://www.yenisafak.com/rss", name: "Yeni Safak" },
    ],
  },
  {
    code: "GH",
    name: "Ghana",
    lat: 7.9,
    lng: -1,
    fallbackFeeds: [
      { url: "https://www.myjoyonline.com/feed/", name: "MyJoyOnline" },
      { url: "https://3news.com/feed.xml", name: "3News" },
      { url: "https://www.graphic.com.gh/news.feed?type=rss", name: "graphic.com.gh" },
    ],
  },
  {
    code: "ET",
    name: "Ethiopia",
    lat: 9.1,
    lng: 40.5,
    fallbackFeeds: [
      { url: "https://addisfortune.news/feed", name: "addisfortune.news" },
      { url: "https://www.ethiopiaobserver.com/feed/", name: "Ethiopia Observer" },
      { url: "https://www.fanamc.com/english/feed/", name: "Welcome to Fana Media Corporation S.C" },
    ],
  },
  {
    code: "TZ",
    name: "Tanzania",
    lat: -6.4,
    lng: 34.9,
    fallbackFeeds: [
      { url: "https://globalpublishers.co.tz/feed/", name: "Global Publishers" },
      { url: "https://habarileo.co.tz/feed/", name: "HabariLeo" },
      { url: "https://dailynews.co.tz/feed/", name: "Daily News" },
      { url: "https://thechanzo.com/feed/", name: "The Chanzo" },
    ],
  },
  {
    code: "UG",
    name: "Uganda",
    lat: 1.4,
    lng: 32.3,
    fallbackFeeds: [
      { url: "https://nilepost.co.ug/feed", name: "Nilepost News" },
      { url: "https://www.independent.co.ug/feed/", name: "The Independent Uganda:" },
    ],
  },
  {
    code: "ZW",
    name: "Zimbabwe",
    lat: -19,
    lng: 29.2,
    fallbackFeeds: [
      { url: "https://allafrica.com/tools/headlines/rdf/zimbabwe/headlines.rdf", name: "Zimbabwe Independent" },
      { url: "https://thestandard.nz/feed/", name: "Standard" },
    ],
  },
  {
    code: "BW",
    name: "Botswana",
    lat: -22.3,
    lng: 24.7,
    fallbackFeeds: [
      { url: "https://www.sundaystandard.info/feed/", name: "Sunday Standard" },
      { url: "https://www.thegazette.news/feed/", name: "Botswana Gazette" },
    ],
  },
  {
    code: "NA",
    name: "Namibia",
    lat: -23,
    lng: 18.5,
    fallbackFeeds: [
      { url: "https://feeds.nbcnews.com/nbcnews/public/news", name: "NBC" },
    ],
  },
  {
    code: "SN",
    name: "Senegal",
    lat: 14.5,
    lng: -14.5,
    fallbackFeeds: [
      { url: "https://www.leral.net/index.php?preaction=rss", name: "leral.net" },
      { url: "https://senego.com/feed", name: "Senego" },
    ],
  },
  {
    code: "PK",
    name: "Pakistan",
    lat: 30.4,
    lng: 69.3,
    fallbackFeeds: [
      { url: "http://feeds.feedburner.com/daily-express-news-showbiz", name: "Daily Express" },
      { url: "https://tribune.com.pk/feed/home", name: "The Express Tribune" },
      { url: "https://jang.com.pk/rss/1/1", name: "قومی خبریں" },
      { url: "https://newsnblogs.com/feed/", name: "News Blog" },
      { url: "https://www.express.pk/feed/", name: "ایکسپریس اردو" },
    ],
  },
  {
    code: "BD",
    name: "Bangladesh",
    lat: 23.7,
    lng: 90.4,
    fallbackFeeds: [
      { url: "https://www.prothomalo.com/stories.rss", name: "প্রথম আলো" },
      { url: "https://www.tbsnews.net/top-news/rss.xml", name: "The Business Standard" },
      { url: "https://en.prothomalo.com/stories.rss", name: "Prothom Alo English" },
    ],
  },
  {
    code: "MY",
    name: "Malaysia",
    lat: 4.2,
    lng: 101.9,
    fallbackFeeds: [
      { url: "https://www.hmetro.com.my/utama.xml", name: "myMetro" },
      { url: "https://www.bharian.com.my/terkini.xml", name: "BH Berita Harian" },
      { url: "https://thebusinesstimes.com/feed/", name: "Business Times" },
    ],
  },
  {
    code: "VN",
    name: "Vietnam",
    lat: 14.1,
    lng: 108.3,
    fallbackFeeds: [
      { url: "https://vnexpress.net/rss/kinh-doanh.rss", name: "VnExpress" },
    ],
  },
  {
    code: "HK",
    name: "Hong Kong",
    lat: 22.3,
    lng: 114.2,
    fallbackFeeds: [
      { url: "http://feeds.feedburner.com/123greetings-daily-rss", name: "Orient Daily" },
      { url: "https://hongkongfp.com/feed/", name: "Hong Kong Free Press HKFP" },
      { url: "http://feeds.hongkongnews.net/rss/b82693edf38ebff8", name: "hongkongnews.net latest rss headlines" },
    ],
  },
  {
    code: "NZ",
    name: "New Zealand",
    lat: -40.9,
    lng: 174.9,
    fallbackFeeds: [
      { url: "https://www.nzherald.co.nz/arc/outboundfeeds/rss/section/nz/?outputType=xml&_website=nzh", name: "NZ Herald" },
      { url: "https://www.rnz.co.nz/rss/national.xml", name: "RNZ New Zealand Headlines" },
      { url: "https://www.nzherald.co.nz/arc/outboundfeeds/rss/curated/78/?outputType=xml", name: "New Zealand Herald" },
      { url: "https://thespinoff.co.nz/feed", name: "The Spinoff" },
      { url: "https://www.1news.co.nz/arc/outboundfeeds/rss/?outputType=xml", name: "1 News" },
    ],
  },
  {
    code: "CL",
    name: "Chile",
    lat: -35.7,
    lng: -71.5,
    fallbackFeeds: [
      { url: "https://feeds.feedburner.com/radiobiobio/NNeJ", name: "BioBioChile" },
      { url: "https://www.theclinic.cl/feed/", name: "The Clinic" },
      { url: "https://www.df.cl/noticias/site/list/port/rss.xml", name: "Diario Financiero" },
      { url: "https://www.publimetro.cl/arc/outboundfeeds/rss/?outputType=xml", name: "Publimetro" },
      { url: "https://elsiglo.cl/feed/", name: "El Siglo" },
      { url: "https://www.lanacion.cl/feed/", name: "La Nación" },
    ],
  },
  {
    code: "PE",
    name: "Peru",
    lat: -9.2,
    lng: -75,
    fallbackFeeds: [
      { url: "https://elcomercio.pe/arc/outboundfeeds/rss/?outputType=xml", name: "El Comercio Perú" },
      { url: "https://gestion.pe/arc/outboundfeeds/rss/?outputType=xml", name: "Gestión" },
      { url: "https://trome.com/arc/outboundfeeds/rss/?outputType=xml", name: "Trome" },
      { url: "https://larepublica.pe/rss/home.xml", name: "La República" },
      { url: "https://diariocorreo.pe/arc/outboundfeeds/rss/?outputType=xml", name: "Diario Correo" },
      { url: "https://losandes.com.pe/feed/", name: "Los Andes" },
      { url: "https://libero.pe/rss/home.xml", name: "Libero" },
    ],
  },
  {
    code: "VE",
    name: "Venezuela",
    lat: 6.4,
    lng: -66.6,
    fallbackFeeds: [
      { url: "https://efectococuyo.com/feed/", name: "Efecto Cocuyo" },
      { url: "https://www.elnacional.com/feed/", name: "EL NACIONAL" },
      { url: "https://2001online.com/feed", name: "2001online.com - Últimas noticias" },
      { url: "https://www.el-carabobeno.com/feed/", name: "El Carabobeño" },
    ],
  },
  {
    code: "CU",
    name: "Cuba",
    lat: 21.5,
    lng: -77.8,
    fallbackFeeds: [
      { url: "https://www.cubanet.org/feed/", name: "CubaNet" },
      { url: "https://diariodecuba.com/rss.xml", name: "Diario de Cuba" },
    ],
  },
  {
    code: "AD",
    name: "Andorra",
    lat: 42.5,
    lng: 1.5,
    fallbackFeeds: [
      { url: "https://www.fotomac.com.tr/rss/anasayfa.xml", name: "ANA" },
      { url: "https://www.bondia.ad/rss.xml", name: "Diari Més" },
    ],
  },
  {
    code: "AF",
    name: "Afghanistan",
    lat: 33.9,
    lng: 67.7,
    fallbackFeeds: [
      { url: "https://pa.azadiradio.com/api/epiqq", name: "Azadi Radio Pashto" },
    ],
  },
  {
    code: "AL",
    name: "Albania",
    lat: 41.2,
    lng: 20.2,
    fallbackFeeds: [
      { url: "https://www.balkanweb.com/feed/", name: "Balkanweb.com &#8211; News24" },
      { url: "https://euronews.al/en/feed/", name: "Euronews Albania" },
    ],
  },
  {
    code: "AM",
    name: "Armenia",
    lat: 40.1,
    lng: 45,
    fallbackFeeds: [
      { url: "https://en.1in.am/feed", name: "1in.am" },
      { url: "https://en.aravot.am/feed/", name: "Aravot" },
    ],
  },
  {
    code: "AZ",
    name: "Azerbaijan",
    lat: 40.1,
    lng: 47.6,
    fallbackFeeds: [
      { url: "https://news.day.az/rss/all.rss", name: "Day.az" },
      { url: "https://news.milli.az/rss/", name: "Milli.az" },
    ],
  },
  {
    code: "BA",
    name: "Bosnia and Herzegovina",
    lat: 43.9,
    lng: 17.7,
    fallbackFeeds: [
      { url: "https://www.dnevnik.ba/rss.xml", name: "Dnevnik.ba" },
    ],
  },
  {
    code: "BB",
    name: "Barbados",
    lat: 13.2,
    lng: -59.5,
    fallbackFeeds: [
      { url: "http://barbadostoday.bb/feed/", name: "barbados Today" },
    ],
  },
  {
    code: "BI",
    name: "Burundi",
    lat: -3.4,
    lng: 29.9,
    fallbackFeeds: [
      { url: "http://www.iwacu-burundi.org/feed/", name: "IWACU" },
    ],
  },
  {
    code: "BJ",
    name: "Benin",
    lat: 9.3,
    lng: 2.3,
    fallbackFeeds: [
      { url: "https://www.24haubenin.info/spip.php?page=backend", name: "24 HEURES AU BENIN" },
      { url: "https://lanouvelletribune.info/feed/", name: "La Nouvelle Tribune" },
      { url: "https://beninwebtv.com/feed.xml", name: "BENIN WEB TV" },
    ],
  },
  {
    code: "BM",
    name: "Bermuda",
    lat: 32.3,
    lng: -64.8,
    fallbackFeeds: [
      { url: "https://bernews.com/feed/", name: "Bernews" },
    ],
  },
  {
    code: "BO",
    name: "Bolivia",
    lat: -16.3,
    lng: -63.6,
    fallbackFeeds: [
      { url: "https://www.opinion.com.bo/rss/", name: "Opinion" },
      { url: "https://www.la-epoca.com.bo/feed/", name: "La Epoca" },
      { url: "https://lapatria.bo/feed/", name: "La Patria" },
    ],
  },
  {
    code: "BS",
    name: "Bahamas",
    lat: 25,
    lng: -77.4,
    fallbackFeeds: [
      { url: "https://www.tribune242.com/rss/headlines/", name: "tribune242.com stories" },
      { url: "https://ewnews.com/feed/", name: "Eye Witness News" },
      { url: "https://ournews.bs/feed/", name: "Our News" },
    ],
  },
  {
    code: "BY",
    name: "Belarus",
    lat: 53.7,
    lng: 27.6,
    fallbackFeeds: [
      { url: "https://charter97.org/rss.php", name: "Новости Беларуси - Хартия'97" },
      { url: "https://news.zerkalo.io/rss/all.rss", name: "ZERKALO.IO: Новости" },
      { url: "https://belta.by/rss/", name: "RSS БелТА" },
    ],
  },
  {
    code: "BZ",
    name: "Belize",
    lat: 17.2,
    lng: -88.5,
    fallbackFeeds: [
      { url: "https://amandala.com.bz/news/feed/", name: "Amandala Newspaper" },
      { url: "https://www.7newsbelize.com/rss.php", name: "7 News" },
      { url: "https://www.breakingbelizenews.com/feed/", name: "Belize News and Opinion on www.breakingbelizenews.com" },
    ],
  },
  {
    code: "CD",
    name: "DR Congo",
    lat: -4,
    lng: 21.8,
    fallbackFeeds: [
      { url: "https://www.congoplanet.com/feeds/rss_congo_africa.xml", name: "Congo Planet" },
    ],
  },
  {
    code: "CM",
    name: "Cameroon",
    lat: 7.4,
    lng: 12.4,
    fallbackFeeds: [
      { url: "https://allafrica.com/tools/headlines/rdf/cameroon/headlines.rdf", name: "AllAfrica Cameroon" },
    ],
  },
  {
    code: "CR",
    name: "Costa Rica",
    lat: 9.7,
    lng: -83.8,
    fallbackFeeds: [
      { url: "https://ticotimes.net/feed", name: "The Tico Times | Costa Rica News | Travel | Real Estate" },
      { url: "https://www.nacion.com/arc/outboundfeeds/rss/?outputType=xml", name: "La Nación" },
    ],
  },
  {
    code: "CY",
    name: "Cyprus",
    lat: 35.1,
    lng: 33.4,
    fallbackFeeds: [
      { url: "https://www.sigmalive.com/rss", name: "Sigma Live" },
      { url: "https://cyprus-mail.com/feed/", name: "Cyprus Mail (English)" },
    ],
  },
  {
    code: "DJ",
    name: "Djibouti",
    lat: 11.8,
    lng: 42.6,
    fallbackFeeds: [
      { url: "https://www.hch24.com/feed/", name: "HCH24" },
    ],
  },
  {
    code: "DK",
    name: "Denmark",
    lat: 56.3,
    lng: 9.5,
    fallbackFeeds: [
      { url: "https://borsen.dk/rss/", name: "Borsen." },
      { url: "https://www.dr.dk/nyheder/service/feeds/allenyheder", name: "Kort nyt | DR" },
      { url: "https://politiken.dk/rss/senestenyt.rss", name: "Politiken.dk - Forsiden" },
    ],
  },
  {
    code: "DM",
    name: "Dominica",
    lat: 15.4,
    lng: -61.4,
    fallbackFeeds: [
      { url: "https://dominicanewsonline.com/news/feed/", name: "Dominica News" },
    ],
  },
  {
    code: "DO",
    name: "Dominican Republic",
    lat: 18.7,
    lng: -70.2,
    fallbackFeeds: [
      { url: "https://dominicantoday.com/feed/", name: "Dominican Today" },
      { url: "https://n.com.do/feed/", name: "N Digital" },
    ],
  },
  {
    code: "DZ",
    name: "Algeria",
    lat: 28,
    lng: 1.7,
    fallbackFeeds: [
      { url: "https://www.algerie360.com/feed/", name: "Algerie360.com" },
      { url: "https://www.tsa-algerie.com/feed/", name: "TSA" },
      { url: "https://www.dzfoot.com/feed", name: "dzFoot.com" },
    ],
  },
  {
    code: "EC",
    name: "Ecuador",
    lat: -1.8,
    lng: -78.2,
    fallbackFeeds: [
      { url: "https://www.elcomercio.com/feed/", name: "El Comercio" },
      { url: "https://www.eluniverso.com/arc/outboundfeeds/rss-subsection/noticias/ecuador/?outputType=xml", name: "El Universo" },
      { url: "https://www.larepublica.ec/feed/", name: "La Republica" },
      { url: "https://www.elheraldo.com.ec/feed/", name: "El Heraldo" },
      { url: "https://elnorte.ec/feed/", name: "El Norte" },
      { url: "https://lagaceta.com.ec/feed/", name: "La Gaceta" },
      { url: "https://cronica.com.ec/feed/", name: "Crónica" },
      { url: "https://manabinoticias.com/feed/", name: "Manabí Noticias" },
      { url: "https://ecoamazonico.com/feed/", name: "ECOAmazónico" },
      { url: "https://www.notiamazonia.com/feed/", name: "Noti Amazonía" },
      { url: "https://quenoticias.com/feed/", name: "Qué!" },
      { url: "https://studiofutbol.com.ec/feed/", name: "StudioFútbol" },
    ],
  },
  {
    code: "EE",
    name: "Estonia",
    lat: 58.6,
    lng: 25,
    fallbackFeeds: [
      { url: "https://www.err.ee/rss", name: "uudised | ERR" },
      { url: "https://news.err.ee/rss", name: "news | ERR" },
      { url: "https://news.postimees.ee/rss", name: "Postimees News" },
    ],
  },
  {
    code: "ER",
    name: "Eritrea",
    lat: 15.2,
    lng: 39.8,
    fallbackFeeds: [
      { url: "https://martinplaut.com/feed/", name: "Martin Plaut" },
    ],
  },
  {
    code: "FI",
    name: "Finland",
    lat: 61.9,
    lng: 25.7,
    fallbackFeeds: [
      { url: "https://yle.fi/rss/uutiset/paauutiset", name: "Yle Uutiset | Pääuutiset" },
      { url: "https://www.hs.fi/rss/tuoreimmat.xml", name: "Uutiset - Helsingin Sanomat" },
      { url: "https://www.iltalehti.fi/rss/uutiset.xml", name: "Iltalehti.fi tuoreimmat uutiset - Uutiset" },
      { url: "https://yle.fi/rss/news", name: "Yle News" },
      { url: "https://www.is.fi/rss/tuoreimmat.xml", name: "Uutiset - Ilta-Sanomat" },
    ],
  },
  {
    code: "FO",
    name: "Faroe Islands",
    lat: 61.9,
    lng: -6.9,
    fallbackFeeds: [
      { url: "https://kvf.fo/rss.xml", name: "Kringvarp Føroya" },
    ],
  },
  {
    code: "GA",
    name: "Gabon",
    lat: -0.8,
    lng: 11.6,
    fallbackFeeds: [
      { url: "https://gabonactu.com/feed/", name: "gabonactu.com" },
      { url: "https://www.gabonreview.com/feed/", name: "Gabonreview.com | Actualité du Gabon |" },
    ],
  },
  {
    code: "GM",
    name: "Gambia",
    lat: 13.4,
    lng: -15.3,
    fallbackFeeds: [
      { url: "https://standard.gm/feed/", name: "The Standard Newspaper | Gambia" },
    ],
  },
  {
    code: "GN",
    name: "Guinea",
    lat: 9.9,
    lng: -11.8,
    fallbackFeeds: [
      { url: "https://guineenews.org/feed/", name: "Guin&eacute;enews&copy;" },
      { url: "https://guineematin.com/feed/", name: "Guineematin.com" },
      { url: "https://mosaiqueguinee.com/feed/", name: "Mosaiqueguinee.com" },
    ],
  },
  {
    code: "GT",
    name: "Guatemala",
    lat: 15.8,
    lng: -90.2,
    fallbackFeeds: [
      { url: "https://lahora.gt/feed/", name: "La Hora" },
      { url: "https://republica.com/feed", name: "República - Últimas noticias de Guatemala hoy en vivo" },
      { url: "https://www.prensalibre.com/feed/", name: "Prensa Libre" },
    ],
  },
  {
    code: "GY",
    name: "Guyana",
    lat: 5,
    lng: -59,
    fallbackFeeds: [
      { url: "https://kaieteurnewsonline.com/feed/", name: "Kaieteur News" },
      { url: "https://demerarawaves.com/feed/", name: "Demerara Waves Online News- Guyana" },
    ],
  },
  {
    code: "HR",
    name: "Croatia",
    lat: 45.1,
    lng: 15.2,
    fallbackFeeds: [
      { url: "https://www.vecernji.hr/feeds/latest", name: "Latest - Večernji.hr" },
      { url: "https://www.24sata.hr/feeds/aktualno.xml", name: "24sata.hr aktualne vijesti" },
      { url: "https://www.tportal.hr/rss-najnovije.xml", name: "RSS Tportal - najnovije vijesti" },
    ],
  },
  {
    code: "HT",
    name: "Haiti",
    lat: 19.1,
    lng: -72.3,
    fallbackFeeds: [
      { url: "https://lenouvelliste.com/rss.xml", name: "Le Nouvelliste" },
      { url: "https://haitiantimes.com/feed/", name: "The Haitian Times" },
      { url: "https://www.haitilibre.com/rss-flash-en.xml", name: "Haitilibre.com / Flash infos" },
    ],
  },
  {
    code: "IQ",
    name: "Iraq",
    lat: 33.2,
    lng: 43.7,
    fallbackFeeds: [
      { url: "https://www.iraqinews.com/feed/", name: "Iraqi News" },
    ],
  },
  {
    code: "IR",
    name: "Iran",
    lat: 32.4,
    lng: 53.7,
    fallbackFeeds: [
      { url: "https://www.radiofarda.com/api/", name: "Radiofarda.com" },
      { url: "https://ir.voanews.com/api/zkup_empmy", name: "Voice of America - Iran" },
      { url: "https://www.yjc.ir/fa/rss/allnews", name: "خبرگزاری باشگاه خبرنگاران | آخرین اخبار ایران و جهان | YJC" },
      { url: "https://www.tabnak.ir/fa/rss/allnews", name: "تابناک | TABNAK" },
      { url: "https://www.mehrnews.com/rss", name: "خبرگزاری مهر | اخبار ایران و جهان | Mehr News Agency" },
      { url: "https://www.khabaronline.ir/rss", name: "خبرگزاری خبرآنلاین - آخرین اخبار ایران و جهان | Khabaronline" },
      { url: "https://www.asriran.com/fa/rss/allnews", name: "عصر ايران" },
    ],
  },
  {
    code: "IS",
    name: "Iceland",
    lat: 64.1,
    lng: -21.9,
    fallbackFeeds: [
      { url: "https://www.ruv.is/rss/frettir", name: "RUV" },
      { url: "https://www.feykir.is/feed", name: "Feykir" },
    ],
  },
  {
    code: "JM",
    name: "Jamaica",
    lat: 18.1,
    lng: -77.3,
    fallbackFeeds: [
      { url: "http://jamaica-star.com/feed/news.xml", name: "The Jamaica Star" },
    ],
  },
  {
    code: "JO",
    name: "Jordan",
    lat: 30.6,
    lng: 36.2,
    fallbackFeeds: [
      { url: "https://en.royanews.tv/rss", name: "en.royanews.tv" },
      { url: "https://www.jordannews.jo/rss", name: "Jordan News | Latest News from Jordan, MENA" },
      { url: "https://www.albawaba.com/rss/all", name: "Al Bawaba - Daily Headlines" },
      { url: "https://royanews.tv/rss", name: "royanews.tv" },
    ],
  },
  {
    code: "KG",
    name: "Kyrgyzstan",
    lat: 41.2,
    lng: 74.8,
    fallbackFeeds: [
      { url: "http://www.tazabek.kg/rss/news.rss", name: "Tazabek" },
    ],
  },
  {
    code: "KH",
    name: "Cambodia",
    lat: 12.6,
    lng: 105,
    fallbackFeeds: [
      { url: "https://cambojanews.com/feed/", name: "CamboJA News" },
      { url: "https://phnompenhpost.com/feed/", name: "Phnom Penh Post" },
    ],
  },
  {
    code: "KZ",
    name: "Kazakhstan",
    lat: 48,
    lng: 68,
    fallbackFeeds: [
      { url: "https://tengrinews.kz/news.rss", name: "Tengri News" },
    ],
  },
  {
    code: "LK",
    name: "Sri Lanka",
    lat: 7.9,
    lng: 80.8,
    fallbackFeeds: [
      { url: "https://www.lankahotnews.net/feeds/posts/default?alt=rss", name: "Lanka Hot News" },
      { url: "https://adaderana.lk/rss.xml", name: "Ada Derana English - Featured News" },
    ],
  },
  {
    code: "LR",
    name: "Liberia",
    lat: 6.4,
    lng: -9.4,
    fallbackFeeds: [
      { url: "https://newrepublic.com/rss.xml", name: "New Republic" },
    ],
  },
  {
    code: "LU",
    name: "Luxembourg",
    lat: 49.8,
    lng: 6.1,
    fallbackFeeds: [
      { url: "https://today.rtl.lu/rss/headlines", name: "Headlines" },
      { url: "https://www.wort.lu/rss/", name: "Luxemburger Wort" },
      { url: "https://www.rtl.lu/rss/headlines", name: "Headlines" },
      { url: "https://lequotidien.lu/feed/", name: "Le Quotidien" },
    ],
  },
  {
    code: "LY",
    name: "Libya",
    lat: 26.3,
    lng: 17.2,
    fallbackFeeds: [
      { url: "https://libyaupdate.com/feed/", name: "Libya Update News" },
      { url: "https://libyaherald.com/feed/", name: "Libya Herald" },
    ],
  },
  {
    code: "MC",
    name: "Monaco",
    lat: 43.7,
    lng: 7.4,
    fallbackFeeds: [
      { url: "https://www.monaco-tribune.com/en/feed/", name: "Monaco Tribune" },
    ],
  },
  {
    code: "MD",
    name: "Moldova",
    lat: 47.4,
    lng: 28.4,
    fallbackFeeds: [
      { url: "https://point.md/ru/rss/novosti/", name: "Point" },
      { url: "https://moldova1.md/rss", name: "Moldova1" },
      { url: "https://www.zdg.md/feed/atom/", name: "Ziarul de Gardă (ZdG)" },
    ],
  },
  {
    code: "ME",
    name: "Montenegro",
    lat: 42.7,
    lng: 19.4,
    fallbackFeeds: [
      { url: "https://www.cdm.me/feed/", name: "CDM Cafe Del Montenegro" },
      { url: "https://rss.portalanalitika.me/", name: "Analitika" },
      { url: "https://rss.aktuelno.me/", name: "Actualno.me" },
      { url: "https://rtnk.me/feed/", name: "RTVNK" },
      { url: "http://www.radiodux.me/rss.xml", name: "RadioDux" },
      { url: "https://radiotitograd.me/feed/", name: "RadioTitograd" },
      { url: "https://espona.me/index.php?format=feed&type=atom", name: "Espona" },
      { url: "https://svetigora.com/feed/", name: "Svetigora" },
      { url: "https://bokanews.me/feed/", name: "BokaNews" },
      { url: "https://www.novineniksica.me/feed/", name: "NovineNiikšića" },
      { url: "https://www.pvinformer.me/feed/", name: "PVInformer" },
      { url: "https://pvportal.me/feed/", name: "PVPortal" },
      { url: "https://radioberane.me/feed/", name: "RadioBerane" },
      { url: "https://mne.ul-info.com/feed/", name: "ULInfo" },
      { url: "https://barinfo.me/feed/", name: "RadioBar" },
    ],
  },
  {
    code: "MG",
    name: "Madagascar",
    lat: -18.8,
    lng: 46.9,
    fallbackFeeds: [
      { url: "https://newsmada.com/feed/", name: "Newsmada" },
      { url: "https://www.madagascar-tribune.com/spip.php?page=backend", name: "Madagascar-Tribune.com" },
      { url: "https://midi-madagasikara.mg/feed/", name: "Midi Madagasikara" },
    ],
  },
  {
    code: "MK",
    name: "North Macedonia",
    lat: 41.5,
    lng: 21.7,
    fallbackFeeds: [
      { url: "https://www.mrt.com.mk/rss.xml", name: "Makedonska Radio Televizija (MRT)" },
    ],
  },
  {
    code: "ML",
    name: "Mali",
    lat: 17.6,
    lng: -4,
    fallbackFeeds: [
      { url: "https://www.studiotamani.org/feed", name: "studiotamani.org" },
      { url: "https://malijet.com/rss", name: "Malijet - Actualites du Mali" },
      { url: "https://bamada.net/feed", name: "Bamada.net" },
    ],
  },
  {
    code: "MM",
    name: "Myanmar",
    lat: 21.9,
    lng: 95.9,
    fallbackFeeds: [
      { url: "https://www.irrawaddy.com/feed", name: "The Irrawaddy" },
    ],
  },
  {
    code: "MN",
    name: "Mongolia",
    lat: 46.9,
    lng: 103.8,
    fallbackFeeds: [
      { url: "https://ikon.mn/rss", name: "iKon.mn - Шинэ мэдээ" },
    ],
  },
  {
    code: "MT",
    name: "Malta",
    lat: 35.9,
    lng: 14.4,
    fallbackFeeds: [
      { url: "http://feed.gozonews.com/GozoNews", name: "Gozo News" },
    ],
  },
  {
    code: "MU",
    name: "Mauritius",
    lat: -20.3,
    lng: 57.6,
    fallbackFeeds: [
      { url: "https://defimedia.info/rss.xml", name: "Défimedia" },
      { url: "https://newsmoris.com/feed/", name: "News Moris" },
    ],
  },
  {
    code: "MV",
    name: "Maldives",
    lat: 3.2,
    lng: 73.2,
    fallbackFeeds: [
      { url: "https://sun.mv/feed/", name: "Sun.mv" },
    ],
  },
  {
    code: "MW",
    name: "Malawi",
    lat: -13.3,
    lng: 34.3,
    fallbackFeeds: [
      { url: "http://www.nyasatimes.com/feed/", name: "Nyasa Times" },
      { url: "http://www.nyasatimes.com/category/national/feed/", name: "Malawi Nation" },
    ],
  },
  {
    code: "NE",
    name: "Niger",
    lat: 17.6,
    lng: 8.1,
    fallbackFeeds: [
      { url: "https://nigerinter.com/feed/", name: "Nigerinter" },
      { url: "https://airinfoagadez.com/feed/", name: "Aïr Info" },
      { url: "https://tamtaminfo.com/feed/", name: "Tamtaminfo" },
    ],
  },
  {
    code: "NI",
    name: "Nicaragua",
    lat: 12.9,
    lng: -85.2,
    fallbackFeeds: [
      { url: "https://confidencial.digital/feed/", name: "Confidencial" },
      { url: "https://despacho505.com/feed/", name: "DESPACHO 505" },
    ],
  },
  {
    code: "NP",
    name: "Nepal",
    lat: 28.4,
    lng: 84.1,
    fallbackFeeds: [
      { url: "https://www.onlinekhabar.com/feed", name: "Online Khabar" },
      { url: "https://english.onlinekhabar.com/feed", name: "OnlineKhabar English News" },
      { url: "https://kathmandupost.com/rss", name: "Kathamndu post RSS" },
      { url: "https://risingnepaldaily.com/rss", name: "The Rising Nepal | Nepal's First English Broadsheet Daily." },
    ],
  },
  {
    code: "PA",
    name: "Panama",
    lat: 8.5,
    lng: -80.8,
    fallbackFeeds: [
      { url: "https://www.tvn-2.com/rss/", name: "Tvn Panamá - Portada" },
      { url: "https://www.prensa.com/arc/outboundfeeds/rss/?outputType=xml", name: "La Prensa" },
      { url: "https://newsroompanama.com/feed/", name: "Newsroom Panama" },
    ],
  },
  {
    code: "PR",
    name: "Puerto Rico",
    lat: 18.2,
    lng: -66.6,
    fallbackFeeds: [
      { url: "https://www.elnuevodia.com/arc/outboundfeeds/rss/?outputType=xml", name: "El Nuevo Día" },
      { url: "https://www.primerahora.com/arc/outboundfeeds/rss/?outputType=xml", name: "Primera Hora" },
      { url: "https://newsismybusiness.com/feed/", name: "News is My Business" },
      { url: "https://www.metro.pr/arc/outboundfeeds/rss/?outputType=xml", name: "Metro Puerto Rico" },
    ],
  },
  {
    code: "PS",
    name: "Palestine",
    lat: 31.9,
    lng: 35.2,
    fallbackFeeds: [
      { url: "https://english.palinfo.com/feed/", name: "The Palestinian Information Center" },
      { url: "https://www.maannews.net/rss", name: "وكالة معا الاخبارية" },
    ],
  },
  {
    code: "SB",
    name: "Solomon Islands",
    lat: -9.6,
    lng: 160.2,
    fallbackFeeds: [
      { url: "https://www.sibconline.com.sb/feed/", name: "SIBC News" },
      { url: "https://www.solomonstarnews.com/feed/", name: "Solomon Star News" },
      { url: "https://theislandsun.com.sb/feed/", name: "Theislandsun" },
    ],
  },
  {
    code: "SL",
    name: "Sierra Leone",
    lat: 8.5,
    lng: -11.8,
    fallbackFeeds: [
      { url: "https://thecalabashnewspaper.com/feed", name: "The Calabash Newspaper" },
      { url: "https://sierraloaded.sl/feed/", name: "Sierraloaded" },
    ],
  },
  {
    code: "SM",
    name: "San Marino",
    lat: 43.9,
    lng: 12.5,
    fallbackFeeds: [
      { url: "https://www.libertas.sm/feed/", name: "libertas" },
    ],
  },
  {
    code: "SO",
    name: "Somalia",
    lat: 5.2,
    lng: 46.2,
    fallbackFeeds: [
      { url: "http://feeds.feedburner.com/waagacusubmedia", name: "Waagacusub Media" },
    ],
  },
  {
    code: "SR",
    name: "Suriname",
    lat: 3.9,
    lng: -56,
    fallbackFeeds: [
      { url: "https://www.waterkant.net/feed/", name: "Waterkant.net" },
    ],
  },
  {
    code: "SY",
    name: "Syria",
    lat: 34.8,
    lng: 38.9,
    fallbackFeeds: [
      { url: "https://sana.sy/tr/feed/", name: "SANA" },
    ],
  },
  {
    code: "TG",
    name: "Togo",
    lat: 8.6,
    lng: 1.2,
    fallbackFeeds: [
      { url: "https://www.jeuneafrique.com/feed/", name: "Jeune Afrique Togo" },
    ],
  },
  {
    code: "TN",
    name: "Tunisia",
    lat: 33.9,
    lng: 9.5,
    fallbackFeeds: [
      { url: "https://www.lapresse.tn/feed/", name: "La Presse de Tunisie" },
    ],
  },
  {
    code: "UY",
    name: "Uruguay",
    lat: -32.5,
    lng: -55.8,
    fallbackFeeds: [
      { url: "https://ladiaria.com.uy/feeds/articulos/", name: "La Diaria" },
      { url: "https://www.xn--lamaana-7za.uy/feed/", name: "La Mañana" },
    ],
  },
  {
    code: "UZ",
    name: "Uzbekistan",
    lat: 41.4,
    lng: 64.6,
    fallbackFeeds: [
      { url: "https://www.gazeta.uz/oz/rss/", name: "Gazeta.uz" },
    ],
  },
  {
    code: "WS",
    name: "Samoa",
    lat: -13.8,
    lng: -172.1,
    fallbackFeeds: [
      { url: "https://www.samoanews.com/?q=rss.xml&quicktabs_3=0", name: "Samoa News" },
    ],
  },
  {
    code: "XK",
    name: "Kosovo",
    lat: 42.6,
    lng: 20.9,
    fallbackFeeds: [
      { url: "https://www.koha.net/rss", name: "KOHA.net" },
      { url: "https://telegrafi.com/feeds/feed.rss?geo=SG", name: "Telegrafi" },
    ],
  },
  {
    code: "YE",
    name: "Yemen",
    lat: 15.6,
    lng: 48.5,
    fallbackFeeds: [
      { url: "https://hshd-ye.net/rss.php", name: "hshd.net" },
    ],
  },
  {
    code: "ZM",
    name: "Zambia",
    lat: -13.1,
    lng: 27.8,
    fallbackFeeds: [
      { url: "https://tumfweko.com/feed/", name: "Tumfweko" },
      { url: "https://nypost.com/feed/", name: "Post" },
    ],
  },
];

export const COUNTRY_BY_CODE = new Map(COUNTRIES.map((c) => [c.code, c]));
