// Comprehensive country feed data: 150 countries
// Countries with Google News editions use those; others use direct RSS fallback feeds

export interface CountryData {
  code: string;
  name: string;
  lat: number;
  lng: number;
  // Google News params (if supported)
  gl?: string;
  ceid?: string;
  hl?: string;
  // Fallback RSS feeds for countries without Google News
  fallbackFeeds?: string[];
}

export const COUNTRIES: CountryData[] = [
  // --- Google News supported countries ---
  { code: "US", name: "United States", lat: 39.8, lng: -98.5, gl: "US", ceid: "US:en", hl: "en-US" },
  { code: "GB", name: "United Kingdom", lat: 54.0, lng: -2.0, gl: "GB", ceid: "GB:en", hl: "en-GB" },
  { code: "IN", name: "India", lat: 20.6, lng: 78.9, gl: "IN", ceid: "IN:en", hl: "en-IN" },
  { code: "AU", name: "Australia", lat: -25.3, lng: 133.8, gl: "AU", ceid: "AU:en", hl: "en-AU" },
  { code: "CA", name: "Canada", lat: 56.1, lng: -106.3, gl: "CA", ceid: "CA:en", hl: "en-CA" },
  { code: "DE", name: "Germany", lat: 51.2, lng: 10.4, gl: "DE", ceid: "DE:en", hl: "en" },
  { code: "FR", name: "France", lat: 46.2, lng: 2.2, gl: "FR", ceid: "FR:en", hl: "en" },
  { code: "JP", name: "Japan", lat: 36.2, lng: 138.3, gl: "JP", ceid: "JP:en", hl: "en" },
  { code: "BR", name: "Brazil", lat: -14.2, lng: -51.9, gl: "BR", ceid: "BR:pt-419", hl: "pt-BR" },
  { code: "MX", name: "Mexico", lat: 23.6, lng: -102.6, gl: "MX", ceid: "MX:es-419", hl: "es-MX" },
  { code: "ZA", name: "South Africa", lat: -30.6, lng: 22.9, gl: "ZA", ceid: "ZA:en", hl: "en-ZA" },
  { code: "NG", name: "Nigeria", lat: 9.1, lng: 8.7, gl: "NG", ceid: "NG:en", hl: "en-NG" },
  { code: "KE", name: "Kenya", lat: -0.02, lng: 37.9, gl: "KE", ceid: "KE:en", hl: "en-KE" },
  { code: "EG", name: "Egypt", lat: 26.8, lng: 30.8, gl: "EG", ceid: "EG:en", hl: "en" },
  { code: "IL", name: "Israel", lat: 31.0, lng: 34.9, gl: "IL", ceid: "IL:en", hl: "en-IL" },
  { code: "AE", name: "UAE", lat: 23.4, lng: 53.8, gl: "AE", ceid: "AE:en", hl: "en" },
  { code: "SA", name: "Saudi Arabia", lat: 23.9, lng: 45.1, gl: "SA", ceid: "SA:en", hl: "en" },
  { code: "KR", name: "South Korea", lat: 35.9, lng: 127.8, gl: "KR", ceid: "KR:en", hl: "en" },
  { code: "SG", name: "Singapore", lat: 1.35, lng: 103.8, gl: "SG", ceid: "SG:en", hl: "en-SG" },
  { code: "ID", name: "Indonesia", lat: -0.8, lng: 113.9, gl: "ID", ceid: "ID:en", hl: "en-ID" },
  { code: "RU", name: "Russia", lat: 61.5, lng: 105.3, gl: "RU", ceid: "RU:en", hl: "en" },
  { code: "IT", name: "Italy", lat: 41.9, lng: 12.6, gl: "IT", ceid: "IT:en", hl: "en" },
  { code: "ES", name: "Spain", lat: 40.5, lng: -3.7, gl: "ES", ceid: "ES:en", hl: "en" },
  { code: "PL", name: "Poland", lat: 51.9, lng: 19.1, gl: "PL", ceid: "PL:en", hl: "en" },
  { code: "UA", name: "Ukraine", lat: 48.4, lng: 31.2, gl: "UA", ceid: "UA:en", hl: "en" },
  { code: "AR", name: "Argentina", lat: -38.4, lng: -63.6, gl: "AR", ceid: "AR:es-419", hl: "es-AR" },
  { code: "CO", name: "Colombia", lat: 4.6, lng: -74.3, gl: "CO", ceid: "CO:es-419", hl: "es-CO" },
  { code: "PH", name: "Philippines", lat: 12.9, lng: 121.8, gl: "PH", ceid: "PH:en", hl: "en-PH" },
  { code: "TW", name: "Taiwan", lat: 23.7, lng: 121.0, gl: "TW", ceid: "TW:en", hl: "en-TW" },
  { code: "TH", name: "Thailand", lat: 15.9, lng: 100.5, gl: "TH", ceid: "TH:en", hl: "en" },
  { code: "AT", name: "Austria", lat: 47.5, lng: 14.6, gl: "AT", ceid: "AT:de", hl: "de" },
  { code: "CH", name: "Switzerland", lat: 46.8, lng: 8.2, gl: "CH", ceid: "CH:de", hl: "de" },
  { code: "BE", name: "Belgium", lat: 50.9, lng: 4.4, gl: "BE", ceid: "BE:fr", hl: "fr" },
  { code: "NL", name: "Netherlands", lat: 52.1, lng: 5.3, gl: "NL", ceid: "NL:nl", hl: "nl" },
  { code: "IE", name: "Ireland", lat: 53.1, lng: -7.7, gl: "IE", ceid: "IE:en", hl: "en" },
  { code: "PT", name: "Portugal", lat: 39.4, lng: -8.2, gl: "PT", ceid: "PT:pt-150", hl: "pt-PT" },
  { code: "SE", name: "Sweden", lat: 60.1, lng: 18.6, gl: "SE", ceid: "SE:sv", hl: "sv" },
  { code: "NO", name: "Norway", lat: 60.5, lng: 8.5, gl: "NO", ceid: "NO:no", hl: "no" },
  { code: "CZ", name: "Czechia", lat: 49.8, lng: 15.5, gl: "CZ", ceid: "CZ:cs", hl: "cs" },
  { code: "SK", name: "Slovakia", lat: 48.7, lng: 19.7, gl: "SK", ceid: "SK:sk", hl: "sk" },
  { code: "HU", name: "Hungary", lat: 47.2, lng: 19.5, gl: "HU", ceid: "HU:hu", hl: "hu" },
  { code: "RO", name: "Romania", lat: 45.9, lng: 24.9, gl: "RO", ceid: "RO:ro", hl: "ro" },
  { code: "BG", name: "Bulgaria", lat: 42.7, lng: 25.5, gl: "BG", ceid: "BG:bg", hl: "bg" },
  { code: "RS", name: "Serbia", lat: 44.0, lng: 21.0, gl: "RS", ceid: "RS:sr", hl: "sr" },
  { code: "SI", name: "Slovenia", lat: 46.2, lng: 15.0, gl: "SI", ceid: "SI:sl", hl: "sl" },
  { code: "LV", name: "Latvia", lat: 56.9, lng: 24.6, gl: "LV", ceid: "LV:lv", hl: "lv" },
  { code: "LT", name: "Lithuania", lat: 55.2, lng: 23.9, gl: "LT", ceid: "LT:lt", hl: "lt" },
  { code: "GR", name: "Greece", lat: 39.1, lng: 21.8, gl: "GR", ceid: "GR:el", hl: "el" },
  { code: "LB", name: "Lebanon", lat: 33.9, lng: 35.9, gl: "LB", ceid: "LB:ar", hl: "ar" },
  { code: "MA", name: "Morocco", lat: 31.8, lng: -7.1, gl: "MA", ceid: "MA:fr", hl: "fr" },
  { code: "TR", name: "Turkey", lat: 39.0, lng: 35.2, gl: "TR", ceid: "TR:tr", hl: "tr" },
  { code: "GH", name: "Ghana", lat: 7.9, lng: -1.0, gl: "GH", ceid: "GH:en", hl: "en" },
  { code: "ET", name: "Ethiopia", lat: 9.1, lng: 40.5, gl: "ET", ceid: "ET:en", hl: "en" },
  { code: "TZ", name: "Tanzania", lat: -6.4, lng: 34.9, gl: "TZ", ceid: "TZ:en", hl: "en" },
  { code: "UG", name: "Uganda", lat: 1.4, lng: 32.3, gl: "UG", ceid: "UG:en", hl: "en" },
  { code: "ZW", name: "Zimbabwe", lat: -19.0, lng: 29.2, gl: "ZW", ceid: "ZW:en", hl: "en" },
  { code: "BW", name: "Botswana", lat: -22.3, lng: 24.7, gl: "BW", ceid: "BW:en", hl: "en" },
  { code: "NA", name: "Namibia", lat: -23.0, lng: 18.5, gl: "NA", ceid: "NA:en", hl: "en" },
  { code: "SN", name: "Senegal", lat: 14.5, lng: -14.5, gl: "SN", ceid: "SN:fr", hl: "fr" },
  { code: "PK", name: "Pakistan", lat: 30.4, lng: 69.3, gl: "PK", ceid: "PK:en", hl: "en" },
  { code: "BD", name: "Bangladesh", lat: 23.7, lng: 90.4, gl: "BD", ceid: "BD:bn", hl: "bn" },
  { code: "MY", name: "Malaysia", lat: 4.2, lng: 101.9, gl: "MY", ceid: "MY:en", hl: "en" },
  { code: "VN", name: "Vietnam", lat: 14.1, lng: 108.3, gl: "VN", ceid: "VN:vi", hl: "vi" },
  { code: "HK", name: "Hong Kong", lat: 22.3, lng: 114.2, gl: "HK", ceid: "HK:zh-Hant", hl: "zh-HK" },
  { code: "NZ", name: "New Zealand", lat: -40.9, lng: 174.9, gl: "NZ", ceid: "NZ:en", hl: "en" },
  { code: "CL", name: "Chile", lat: -35.7, lng: -71.5, gl: "CL", ceid: "CL:es-419", hl: "es-419" },
  { code: "PE", name: "Peru", lat: -9.2, lng: -75.0, gl: "PE", ceid: "PE:es-419", hl: "es-419" },
  { code: "VE", name: "Venezuela", lat: 6.4, lng: -66.6, gl: "VE", ceid: "VE:es-419", hl: "es-419" },
  { code: "CU", name: "Cuba", lat: 21.5, lng: -77.8, gl: "CU", ceid: "CU:es-419", hl: "es-419" },

  // --- Fallback-only countries (direct RSS feeds) ---
  { code: "AF", name: "Afghanistan", lat: 33.9, lng: 67.7, fallbackFeeds: ["http://pa.azadiradio.org/api/epiqq"] },
  { code: "AL", name: "Albania", lat: 41.2, lng: 20.2, fallbackFeeds: ["http://www.balkanweb.com/site/feed/"] },
  { code: "AD", name: "Andorra", lat: 42.5, lng: 1.5, fallbackFeeds: ["http://www.bondia.ad/rss.xml"] },
  { code: "AM", name: "Armenia", lat: 40.1, lng: 45.0, fallbackFeeds: ["http://news.am/eng/rss/", "http://en.aravot.am/feed/"] },
  { code: "AZ", name: "Azerbaijan", lat: 40.1, lng: 47.6, fallbackFeeds: ["http://news.day.az/rss/all.rss", "http://en.trend.az/feeds/index.rss"] },
  { code: "BA", name: "Bosnia and Herzegovina", lat: 43.9, lng: 17.7, fallbackFeeds: ["http://www.dnevnik.ba/rss.xml"] },
  { code: "BB", name: "Barbados", lat: 13.2, lng: -59.5, fallbackFeeds: ["http://www.barbadostoday.bb/feed/"] },
  { code: "BI", name: "Burundi", lat: -3.4, lng: 29.9, fallbackFeeds: ["http://www.iwacu-burundi.org/feed/"] },
  { code: "BJ", name: "Benin", lat: 9.3, lng: 2.3, fallbackFeeds: ["http://mediaf.org/?feed=rss2&tag=charles-honvoh-adjinakou"] },
  { code: "BM", name: "Bermuda", lat: 32.3, lng: -64.8, fallbackFeeds: ["http://bernews.com/tag/rory-field/feed/"] },
  { code: "BO", name: "Bolivia", lat: -16.3, lng: -63.6, fallbackFeeds: ["https://larazon.bo/feed/", "https://www.opinion.com.bo/rss/"] },
  { code: "BS", name: "Bahamas", lat: 25.0, lng: -77.4, fallbackFeeds: ["http://bahamaspress.com/feed/"] },
  { code: "BY", name: "Belarus", lat: 53.7, lng: 27.6, fallbackFeeds: ["http://nn.by/?c=rss-all&lang=en"] },
  { code: "BZ", name: "Belize", lat: 17.2, lng: -88.5, fallbackFeeds: ["http://amandala.com.bz/news/feed/"] },
  { code: "CD", name: "DR Congo", lat: -4.0, lng: 21.8, fallbackFeeds: ["http://www.congoplanet.com/feeds/rss_congo_africa.xml"] },
  { code: "CM", name: "Cameroon", lat: 7.4, lng: 12.4, fallbackFeeds: ["http://allafrica.com/tools/headlines/rdf/cameroon/headlines.rdf"] },
  { code: "CR", name: "Costa Rica", lat: 9.7, lng: -83.8, fallbackFeeds: ["http://www.elfinancierocr.com/rss/"] },
  { code: "CY", name: "Cyprus", lat: 35.1, lng: 33.4, fallbackFeeds: ["http://cyprus-mail.com/feed/", "http://www.sigmalive.com/rss"] },
  { code: "DJ", name: "Djibouti", lat: 11.8, lng: 42.6, fallbackFeeds: ["http://www.nacion.com/rss/"] },
  { code: "DK", name: "Denmark", lat: 56.3, lng: 9.5, fallbackFeeds: ["http://borsen.dk/rss/"] },
  { code: "DM", name: "Dominica", lat: 15.4, lng: -61.4, fallbackFeeds: ["http://dominicanewsonline.com/news/feed/"] },
  { code: "DO", name: "Dominican Republic", lat: 18.7, lng: -70.2, fallbackFeeds: ["http://almomento.net/feed/", "http://acento.com/feed/"] },
  { code: "DZ", name: "Algeria", lat: 28.0, lng: 1.7, fallbackFeeds: ["http://www.algerie360.com/feed/", "http://elkhadra.com/fr/feed/"] },
  { code: "EC", name: "Ecuador", lat: -1.8, lng: -78.2, fallbackFeeds: ["https://www.elcomercio.com/feed/", "https://gk.city/feed/"] },
  { code: "EE", name: "Estonia", lat: 58.6, lng: 25.0, fallbackFeeds: ["http://www.postimees.ee/rss/"] },
  { code: "ER", name: "Eritrea", lat: 15.2, lng: 39.8, fallbackFeeds: ["http://asmarino.com/?format=feed&type=rss"] },
  { code: "FI", name: "Finland", lat: 61.9, lng: 25.7, fallbackFeeds: ["http://yle.fi/uutiset/rss/uutiset.rss?osasto=news"] },
  { code: "FO", name: "Faroe Islands", lat: 61.9, lng: -6.9, fallbackFeeds: ["http://www.npr.org/rss/podcast.php?id=510289"] },
  { code: "GA", name: "Gabon", lat: -0.8, lng: 11.6, fallbackFeeds: ["http://fr.infosgabon.com/feed/"] },
  { code: "GM", name: "Gambia", lat: 13.4, lng: -15.3, fallbackFeeds: ["http://thepoint.gm/posts/rss/xml"] },
  { code: "GN", name: "Guinea", lat: 9.9, lng: -11.8, fallbackFeeds: ["http://guineenews.org/feed/"] },
  { code: "GT", name: "Guatemala", lat: 15.8, lng: -90.2, fallbackFeeds: ["http://www.plazapublica.com.gt/rss"] },
  { code: "GY", name: "Guyana", lat: 5.0, lng: -59.0, fallbackFeeds: ["http://www.kaieteurnewsonline.com/feed/"] },
  { code: "HR", name: "Croatia", lat: 45.1, lng: 15.2, fallbackFeeds: ["http://www.24sata.hr/feeds/news.xml", "http://www.tportal.hr/rss/naslovnicarss.xml"] },
  { code: "HT", name: "Haiti", lat: 19.1, lng: -72.3, fallbackFeeds: ["http://www.haitilibre.com/rss-flash-en.xml"] },
  { code: "IQ", name: "Iraq", lat: 33.2, lng: 43.7, fallbackFeeds: ["http://www.ahewar.org/rss/default.asp?lt=7"] },
  { code: "IR", name: "Iran", lat: 32.4, lng: 53.7, fallbackFeeds: ["http://english.khabaronline.ir/rss/", "http://www.radiofarda.com/api/"] },
  { code: "IS", name: "Iceland", lat: 64.1, lng: -21.9, fallbackFeeds: ["http://www.mbl.is/mbl-frettir-forsida"] },
  { code: "JM", name: "Jamaica", lat: 18.1, lng: -77.3, fallbackFeeds: ["http://jamaica-gleaner.com/feed/rss.xml"] },
  { code: "JO", name: "Jordan", lat: 30.6, lng: 36.2, fallbackFeeds: ["http://www.jordanzad.com/rss.php?type=main"] },
  { code: "KG", name: "Kyrgyzstan", lat: 41.2, lng: 74.8, fallbackFeeds: ["http://www.akipress.com/rss/en.rss"] },
  { code: "KH", name: "Cambodia", lat: 12.6, lng: 105.0, fallbackFeeds: ["http://www.khmer.rfi.fr/cambodia/rss"] },
  { code: "KZ", name: "Kazakhstan", lat: 48.0, lng: 68.0, fallbackFeeds: ["http://tengrinews.kz/news.rss"] },
  { code: "LK", name: "Sri Lanka", lat: 7.9, lng: 80.8, fallbackFeeds: ["http://www.lankahotnews.net/feeds/posts/default?alt=rss"] },
  { code: "LR", name: "Liberia", lat: 6.4, lng: -9.4, fallbackFeeds: ["http://www.newrepublic.com/rss.xml"] },
  { code: "LU", name: "Luxembourg", lat: 49.8, lng: 6.1, fallbackFeeds: ["http://rtl.lu/rss/headlines/"] },
  { code: "LY", name: "Libya", lat: 26.3, lng: 17.2, fallbackFeeds: ["http://www.tripolipost.com/rss.xml"] },
  { code: "MC", name: "Monaco", lat: 43.7, lng: 7.4, fallbackFeeds: ["http://www.montecarlonews.it/links/rss/argomenti/matrimonio-del-principe/rss.xml"] },
  { code: "MD", name: "Moldova", lat: 47.4, lng: 28.4, fallbackFeeds: ["http://point.md/ru/rss/novosti/", "http://www.timpul.md/rss"] },
  { code: "ME", name: "Montenegro", lat: 42.7, lng: 19.4, fallbackFeeds: ["https://www.vijesti.me/rss", "https://www.cdm.me/feed/"] },
  { code: "MG", name: "Madagascar", lat: -18.8, lng: 46.9, fallbackFeeds: ["http://www.madagascar-tribune.com/spip.php?page=backend"] },
  { code: "MK", name: "North Macedonia", lat: 41.5, lng: 21.7, fallbackFeeds: ["http://www.mkd.mk/feed"] },
  { code: "ML", name: "Mali", lat: 17.6, lng: -4.0, fallbackFeeds: ["http://www.journaldumali.com/rss/"] },
  { code: "MM", name: "Myanmar", lat: 21.9, lng: 95.9, fallbackFeeds: ["http://www.irrawaddy.org/feed", "http://myanmargazette.net/feed"] },
  { code: "MN", name: "Mongolia", lat: 46.9, lng: 103.8, fallbackFeeds: ["http://www.bolod.mn/feed.php"] },
  { code: "MT", name: "Malta", lat: 35.9, lng: 14.4, fallbackFeeds: ["http://www.maltatoday.com.mt/rss/"] },
  { code: "MU", name: "Mauritius", lat: -20.3, lng: 57.6, fallbackFeeds: ["http://www.lexpress.mu/rss.xml"] },
  { code: "MV", name: "Maldives", lat: 3.2, lng: 73.2, fallbackFeeds: ["http://sun.mv/feed/"] },
  { code: "MW", name: "Malawi", lat: -13.3, lng: 34.3, fallbackFeeds: ["http://www.nyasatimes.com/feed/"] },
  { code: "NE", name: "Niger", lat: 17.6, lng: 8.1, fallbackFeeds: ["http://www.tamtaminfo.com/feed/"] },
  { code: "NI", name: "Nicaragua", lat: 12.9, lng: -85.2, fallbackFeeds: ["http://nuevaya.com.ni/feed/"] },
  { code: "NP", name: "Nepal", lat: 28.4, lng: 84.1, fallbackFeeds: ["http://www.onlinekhabar.com/feed/"] },
  { code: "PA", name: "Panama", lat: 8.5, lng: -80.8, fallbackFeeds: [] },
  { code: "PR", name: "Puerto Rico", lat: 18.2, lng: -66.6, fallbackFeeds: ["http://noticel.com/feed"] },
  { code: "PS", name: "Palestine", lat: 31.9, lng: 35.2, fallbackFeeds: ["http://www.nablustv.net/xml.asp"] },
  { code: "SB", name: "Solomon Islands", lat: -9.6, lng: 160.2, fallbackFeeds: ["http://www.solomontimes.com/rss/latest-news.xml"] },
  { code: "SL", name: "Sierra Leone", lat: 8.5, lng: -11.8, fallbackFeeds: [] },
  { code: "SM", name: "San Marino", lat: 43.9, lng: 12.5, fallbackFeeds: ["http://giornalesm.com/feed/"] },
  { code: "SO", name: "Somalia", lat: 5.2, lng: 46.2, fallbackFeeds: ["http://www.jowhar.com/?feed=rss2&author=1"] },
  { code: "SR", name: "Suriname", lat: 3.9, lng: -56.0, fallbackFeeds: ["http://www.starnieuws.com/rss/starnieuws.rss"] },
  { code: "SY", name: "Syria", lat: 34.8, lng: 38.9, fallbackFeeds: ["http://www.sana.sy/tr/?feed=rss2"] },
  { code: "TG", name: "Togo", lat: 8.6, lng: 1.2, fallbackFeeds: ["http://feeds2.feedburner.com/Actualite_Togo"] },
  { code: "TN", name: "Tunisia", lat: 33.9, lng: 9.5, fallbackFeeds: ["http://www.leaders.com.tn/rss"] },
  { code: "UY", name: "Uruguay", lat: -32.5, lng: -55.8, fallbackFeeds: ["https://www.elobservador.com.uy/rss/pages/ultimo-momento.xml", "https://ladiaria.com.uy/feeds/articulos"] },
  { code: "UZ", name: "Uzbekistan", lat: 41.4, lng: 64.6, fallbackFeeds: ["http://www.gazeta.uz/rss/"] },
  { code: "WS", name: "Samoa", lat: -13.8, lng: -172.1, fallbackFeeds: ["http://www.samoanews.com/?q=rss.xml"] },
  { code: "XK", name: "Kosovo", lat: 42.6, lng: 20.9, fallbackFeeds: ["https://www.rtklive.com/sq/feed/", "https://zeri.info/rss/zerat"] },
  { code: "YE", name: "Yemen", lat: 15.6, lng: 48.5, fallbackFeeds: ["https://marebpress.net/news_rss.php"] },
  { code: "ZM", name: "Zambia", lat: -13.1, lng: 27.8, fallbackFeeds: ["http://tumfweko.com/feed/"] },
];

// Lookup helpers
export const COUNTRY_BY_CODE = new Map(COUNTRIES.map((c) => [c.code, c]));
